### PR TITLE
fix(useExtractedObservable,watchExtractedObservable): error when extractor is undefined

### PR DESCRIPTION
**Pull request by MstrVLT**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

if useExtractedObservable or watchExtractedObservable extractor returns an undefined value. Errors appear in the console log

### CODE REVIEW

**Comment by MstrVLT** [comment]
Tests were added but had to be removed I haven't found a good way to test this error

**Comment by MstrVLT** [comment]
I also wrote a test, but it's too complicated
https://stackblitz.com/edit/vitest-dev-vitest-fgvmcd?file=test%2Fbasic.test.ts

**Comment by Voltra** [comment]
Hi @MstrVLT !

That is by design as it's meant to always extract/map an observable from the vue reactive value.

IMHO, I think this is more of an XY problem: How to use `useExtractedObservable` and `watchExtractedObservable` if my function is partial and not total?

You can in fact return an empty observable to handle those cases, and in that case the value type should always be `T|undefined`.

These composables were made to behave like `useObservable` and `watch` but lifted to handle more complex cases based on vue reactive data.

The extractor is meant to be a 1-1 mapping (as per the typedef), and not a 1-0/1 mapping

**Comment by Voltra** [comment]
For future reference: I don't mind being tagged in PR/issues regarding the composables I've written.

It'll probably help with intent and might result in adding laravel-style comments to the code (and addendum to the docs) to properly document these kinds of choices

**Comment by antfu** [comment]
Closing due to inactivity. Please open a new issue referencing to this one if you can follow up with more information.

**Pull request closed without merging**
