### PR TITLE
feat: `immediateCallback` for `useTimestamp` & `useRafFn`

### PR DESCRIPTION
**Pull request by Waleed-KH**
### Description

`immediateCallback` option for `useTimestamp` & `useRafFn` functions

### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
Thanks for contribution. I understand the usage but I feel the complexity is not worth for this as it's easy to workaround on the the userland. I'd prefer to now have them for now. Thanks.

**Comment by Waleed-KH** [comment]
the workaround has a down side which is the inability of using inline callback:

```ts
// with the immediateCallback option 
useTimestamp({ immediateCallback: true, callback() {
	// ...
}})

// workaround 
function myCb() {
	// ...
}

useTimestamp({ callback: myCb });
myCb();
```

also it's just an option to invoke the function immediately, so I don't think it add any complexity, and `useIntervalFn` already has it.

**Comment by antfu** [comment]
Yes, but you see, every callback option has this problem and we certainly don't want to add `immediateCallback` to every single function and every single callback. On top of that, I can say with `immediateCallback` make its inability to pass arguments, so maybe we should add `immediateCallbackArgs` as well? We have to justify "how much it cost" and "how much it helps".

I am not saying your usage is not legal. But please understand that one of the maintainers' jobs is to guard designs and try to prevent [Slippery slope](https://en.wikipedia.org/wiki/Slippery_slope) to happen. 

> useIntervalFn already has it

That is a classic one :P - Actually thanks for mentioning it, I would actually consider removing it instead of expanding this idea to every function.

**Comment by Waleed-KH** [comment]
good point 👍

**Pull request closed without merging**
