### PR TITLE
feat(@vueuse/shapes): Add-on with composables for reactive 2D shapes.

### PR DESCRIPTION
**Pull request by marchantweb**
### Description

This PR introduces an add-on at `@vueuse/shapes`. This add-on is a collection of Vue composables for working with reactive 2D shapes, which is especially useful for creative programming projects.

#### Features

- A single `usePolygon` composable that handles most common shapes.
- Standalone composables for non-polygonal shapes like circles and rectangles.
- Composables return refs for edges, vertices, etc.
- Built with Vue Composition API.
- Written in TypeScript.
- Tests for every shape composable.
- No third-party dependencies.

#### The initial composables in this add-on include:

- `useCircle`
- `usePolygon` _(supporting a lot of common equilateral shapes like triangles, squares, pentagons, etc.)_
- `useRectangle`
- `useRhombus`
- `useTriangle` _(supporting non-equilateral triangles)_

### Additional context

All composables except `useCircle` provide a canvas-rendered demo of the shape function with parameters, to quickly demonstrate the use-case of the add-on.

---

### <samp>🤖 Generated by Copilot at f35f891</samp>

This pull request adds a new `shapes` add-on package to the VueUse library, which provides a set of composables for creating and manipulating geometric shapes on a canvas. It includes the source, test, and documentation files for four shape composables: `useCircle`, `usePolygon`, `useRectangle`, and `useRhombus`. It also updates the `packages` array in `./meta/packages.ts` and the `packages/add-ons.md` file to include the new package.

### <samp>🤖 Generated by Copilot at f35f891</samp>

*  Add a new `shapes` add-on package that provides composables for generating and manipulating 2D shapes ([link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-ba987eee71eec89f4467e9bac90f9dfaed53f88fc0302b5a980dc47cb96f1693R157-R166), [link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-3c96f38abeba0dbfc4e7cbae4edea29383a8e43115b3b394be2cfce33784d861R114-R122), [link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-b65f54450637ac2321b38272c5fa45132e376fc31b6fbbd4b8d7bc82fc53909cR1-R5), [link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-cd8fdf6cf4c1d81d160a4dd789a15cdec5b8560654f206ef3f302dc134f09e2aR1-R40), [link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-a19fe099dc852499618c55a350e90819607845fe765375772012e3b7f94955e6R1-R16))
*  Document the features, installation, functions, and license of the `shapes` package in `packages/shapes/README.md` ([link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-1ecdf133063a87b17a2317b2e8aec510f7ed5e762b7edf8d42f9eca14126f7d2R1-R36))
*  Implement and document four shape composables: `useCircle`, `usePolygon`, `useRectangle`, and `useRhombus` in `packages/shapes/useCircle`, `packages/shapes/usePolygon`, `packages/shapes/useRectangle`, and `packages/shapes/useRhombus` respectively ([link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-dd033376c968e02662b6c1f28c061c9147f2f5063e7d83050a9929308f6bab4fR1-R29), [link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-8cd189313445665fd661a96e729e218aa20fdada0d917f5fc4002029e51013d3R1-R38), [link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-85034bde00fa25839179ac3a54c71ef38c6731471a1bdb8d56cdd0518191a353R1-R33), [link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-59ab2682e1c609e1f0ff34ae5a34526143f62982c2ba7da517d79a997f96b423R1-R90), [link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-ec79e0540b0b4bec4066a5fbc1e05c127b430fef39e45cd0084b8c9f314fd8aaR1-R33), [link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-b7e17b6dab8c9bf3de763a2a4a38fc047a0db105bc7e646318b1df8e816aa9f8R1-R97), [link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-125455b94e0031efc579b3c99a8033c6544498a490dbf7dd34c7e32a5edc5d92R1-R46))
*  Add a common CSS file for the demo files in `packages/shapes/demo-styles.css` ([link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-c8756979b387c7ee654c03a2f21136d2dc8a02c4240e7b60e41c9562e46814f5R1-R22))
*  Add a Vue component that renders a canvas with the shape vertices and edges in `packages/shapes/blueprint.vue` ([link](https://github.com/vueuse/vueuse/pull/3528/files?diff=unified&w=0#diff-a25d5d5cc879608fd05a20b01b7c6e8a74070d662a75e6469d03e7021f5c93b3R1-R105))

### CODE REVIEW

**Comment by antfu** [comment]
Thanks a lot for your work, the proposed package looks interesting! However, I am not if we could take it, as we already have too many functions to maintain and entered the "Slow down mode". I'd suggest you create your own package for it and see how the community finds it useful, and so your work won't get blocked by us.

I am closing this for now to make it clear. We are open to further discussion to see how we can help on it. Thanks!

**Comment by marchantweb** [comment]
Absolutely, thanks for your consideration! Have a great one :)

**Comment by marchantweb** [comment]
Hey @antfu - I know you're not a huge fan of comments on closed PRs, but I just wanted to ping you here to say that I've taken your advice and have split this off into it's own library, at [https://vuexyz.org](https://vuexyz.org), in case you wanted to check it out :)

Have a great one! ✨

**Comment by antfu** [comment]
The website is very cool, great job!

**Pull request closed without merging**
