### PR TITLE
feat(nuxt): move to ESM-first and fix types

### PR DESCRIPTION
**Pull request by userquin**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

Move `@vueuse/nuxt` Nuxt module to ESM-only and fix types in Node10 and Node16(cjs).

### Additional context

Cannot test `playgrounds/nuxt` on my Windows laptop with node 18.16.0 LTS:
```shell
 ERROR  Failed to resolve entry for package "@vueuse/rxjs". The package may have incorrect main/module/exports specified in its package.json.          22:03:03  

 ERROR  Failed to resolve entry for package "@vueuse/rxjs". The package may have incorrect main/module/exports specified in its package.json.         22:03:03  
```

Adding `@vueuse/rxjs` to package.json `devDependencies` and `resolutions` and including the `alias` in `nuxt.config.ts`:
<details>
<summary>nuxt error</summary>

```shell
[nuxt] [request error] [unhandled] [500] Cannot find module './internal/Observable'
Require stack:
- D:\work\vueuse\vueuse\playgrounds\nuxt\rxjs
  at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
  at Module._load (node:internal/modules/cjs/loader:920:27)
  at Module.require (node:internal/modules/cjs/loader:1141:19)
  at require (node:internal/modules/cjs/helpers:110:18)
  at D:\work\vueuse\vueuse\playgrounds\nuxt\rxjs:17:20
  at ViteNodeRunner.directRequest (/D:/work/vueuse/vueuse/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.9.0/node_modules/vite-node/dist/client.mjs:341:11)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.cachedRequest (/D:/work/vueuse/vueuse/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.9.0/node_modules/vite-node/dist/client.mjs:197
:14)
  at async ViteNodeRunner.dependencyRequest (/D:/work/vueuse/vueuse/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.9.0/node_modules/vite-node/dist/client.mjs
:231:12)
  at async D:\work\vueuse\vueuse\packages\rxjs\from\index.ts:1:31
[nuxt] [request error] [unhandled] [500] Cannot find module './internal/Observable'
Require stack:
- D:\work\vueuse\vueuse\playgrounds\nuxt\rxjs
  at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
  at Module._load (node:internal/modules/cjs/loader:920:27)
  at Module.require (node:internal/modules/cjs/loader:1141:19)
  at require (node:internal/modules/cjs/helpers:110:18)
  at D:\work\vueuse\vueuse\playgrounds\nuxt\rxjs:17:20
  at ViteNodeRunner.directRequest (/D:/work/vueuse/vueuse/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.9.0/node_modules/vite-node/dist/client.mjs:341:11)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.cachedRequest (/D:/work/vueuse/vueuse/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.9.0/node_modules/vite-node/dist/client.mjs:197
:14)
  at async ViteNodeRunner.dependencyRequest (/D:/work/vueuse/vueuse/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.9.0/node_modules/vite-node/dist/client.mjs
:231:12)
  at async D:\work\vueuse\vueuse\packages\rxjs\from\index.ts:1:31
ℹ nuxt.config.ts updated. Restarting nuxt...
```
</details>

Maybe a problem with Windows filesystem...

Without this PR (check https://arethetypeswrong.github.io/?p=%40vueuse%2Fnuxt%4010.6.1):

imagen

With this PR:

imagen

### CODE REVIEW

**Comment by antfu** [comment]
Ok, let's do dual-format to be safe.

**Comment by userquin** [comment]
I'm going to try testing with Nuxt 2, `index.cjs` changed to fix CJS types using `exports.default` instead `module.exports`: https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseExportDefault.md

**Comment by userquin** [comment]
should we add esm interop to module.cjs ? No idea if jiti/mlly checking for `__esModule`  and `export.default` (Vite for sure)

**Comment by userquin** [comment]
something broken

**Review by antfu — APPROVED** [review]

**Pull request merged**
