### PR TITLE
fix(router): improves router functions: synchronize values, adds tests, and optimize performance

### LINKED ISSUE #3173: useRouteQuery not reactive to navigation
### Describe the bug

If a query parameter is changed (e.g. by `navigateTo`), the resulting object is not changing.

To reproduce:
- Open repro link
- Enter "foo" and press navigate

Expected: param changes to `foo` along with change of URL.
Actual: param remains empty

### Reproduction

https://stackblitz.com/edit/nuxt-starter-hkxvge?file=pages%2Findex.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    @vueuse/router: ^10.2.0 => 10.2.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by anteriovieira**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<be>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

Update values when route hash, params, or query change.

### Additional context

It will change value when the route changes

fixes #3173 #3050 #3160 #3164

---

### <samp>🤖 Generated by Copilot at 7b57a78</samp>

This pull request enhances the reactivity and performance of three router-related functions: `useRouteHash`, `useRouteParams`, and `useRouteQuery`. It refactors them to use proxy variables and watchers to sync their values with the current route object. It also adds or improves the test cases for these functions to verify their expected behavior.

### <samp>🤖 Generated by Copilot at 7b57a78</samp>

*  Refactor `useRouteHash`, `useRouteParams`, and `useRouteQuery` functions to use proxy variables and watchers instead of custom refs ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-fc3a7ce9d8a27367785d6851f036fec95e5b08c3af89152d498b11e8089c8554L22-R59), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-f657fa605a6d4b2a9769faa5835fde4154c39c4a01a09cf8ae63e9dac446fcd8L49-R95), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-3a643af876b64ca6e9d5db979bfc2cfb0af8d46845a7cd6bfe4b1e41e5a369b5L48-R92))
  * Import `watch` function from `vue-demi` to sync the proxy values with the route object when the route changes externally ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-fc3a7ce9d8a27367785d6851f036fec95e5b08c3af89152d498b11e8089c8554L1-R1), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-f657fa605a6d4b2a9769faa5835fde4154c39c4a01a09cf8ae63e9dac446fcd8L1-R5), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-3a643af876b64ca6e9d5db979bfc2cfb0af8d46845a7cd6bfe4b1e41e5a369b5L1-R4))
  * Check if the new values are different from the current ones before updating the route object and triggering the proxy ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-fc3a7ce9d8a27367785d6851f036fec95e5b08c3af89152d498b11e8089c8554L22-R59), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-f657fa605a6d4b2a9769faa5835fde4154c39c4a01a09cf8ae63e9dac446fcd8L49-R95), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-3a643af876b64ca6e9d5db979bfc2cfb0af8d46845a7cd6bfe4b1e41e5a369b5L48-R92))
  * Preserve the current params, query, and hash of the route when updating the route object ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-fc3a7ce9d8a27367785d6851f036fec95e5b08c3af89152d498b11e8089c8554L22-R59), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-f657fa605a6d4b2a9769faa5835fde4154c39c4a01a09cf8ae63e9dac446fcd8L49-R95), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-3a643af876b64ca6e9d5db979bfc2cfb0af8d46845a7cd6bfe4b1e41e5a369b5L48-R92))
  * Cast the proxy variables to the correct types of the hash, param, and query values ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-f657fa605a6d4b2a9769faa5835fde4154c39c4a01a09cf8ae63e9dac446fcd8L49-R95), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-3a643af876b64ca6e9d5db979bfc2cfb0af8d46845a7cd6bfe4b1e41e5a369b5L48-R92))
* Add and update test cases for `useRouteHash`, `useRouteParams`, and `useRouteQuery` functions in `index.test.ts` files ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-82691b0ea2a3b2f357738c7235bb1e21656b0c86f5d8c7acef6f59c07a784d99R65-R75), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-a57f86ebcafcb55d44126c69a48bd1f5c88e513a80fddd3241ecd3ae34ba76ddR146-R194), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-faa7aba85ff895209572d55a507c772d3fbc8ff9530641d792cd69d5eeb0101aR50-R51), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-faa7aba85ff895209572d55a507c772d3fbc8ff9530641d792cd69d5eeb0101aR144-R215))
  * Import `reactive` function from `vue-demi` to make the `getRoute` function return a reactive object ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-82691b0ea2a3b2f357738c7235bb1e21656b0c86f5d8c7acef6f59c07a784d99L1-R6), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-a57f86ebcafcb55d44126c69a48bd1f5c88e513a80fddd3241ecd3ae34ba76ddL1-R7), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-faa7aba85ff895209572d55a507c772d3fbc8ff9530641d792cd69d5eeb0101aL1-R7))
  * Import `vi` object from `vitest` to create mock functions for testing effects ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-a57f86ebcafcb55d44126c69a48bd1f5c88e513a80fddd3241ecd3ae34ba76ddL1-R7), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-faa7aba85ff895209572d55a507c772d3fbc8ff9530641d792cd69d5eeb0101aL1-R7))
  * Use mock router objects to simulate route changes and expect the proxy values to be updated accordingly ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-82691b0ea2a3b2f357738c7235bb1e21656b0c86f5d8c7acef6f59c07a784d99R65-R75), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-a57f86ebcafcb55d44126c69a48bd1f5c88e513a80fddd3241ecd3ae34ba76ddR146-R194), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-faa7aba85ff895209572d55a507c772d3fbc8ff9530641d792cd69d5eeb0101aR144-R215))
  * Check if the functions return the default values when the hash, param, or query keys are not present in the route object ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-faa7aba85ff895209572d55a507c772d3fbc8ff9530641d792cd69d5eeb0101aR50-R51))
  * Check if the functions differentiate null and undefined values ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-faa7aba85ff895209572d55a507c772d3fbc8ff9530641d792cd69d5eeb0101aR144-R215))
  * Check if the functions avoid triggering effects when the values don't change ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-a57f86ebcafcb55d44126c69a48bd1f5c88e513a80fddd3241ecd3ae34ba76ddR146-R194), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-faa7aba85ff895209572d55a507c772d3fbc8ff9530641d792cd69d5eeb0101aR144-R215))
  * Check if the functions keep the current params, query, and hash of the route when updating the route object ([link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-a57f86ebcafcb55d44126c69a48bd1f5c88e513a80fddd3241ecd3ae34ba76ddR146-R194), [link](https://github.com/vueuse/vueuse/pull/3184/files?diff=unified&w=0#diff-faa7aba85ff895209572d55a507c772d3fbc8ff9530641d792cd69d5eeb0101aR144-R215))

### CODE REVIEW

**Comment by antfu** [comment]
Can you check if the changes I made in 3a810cc make sense to you?

When `route.hash` get changed and we sync the data, I don't expect `router.push` to be called again. Even though it might already dedupe, it feels a bit dangerous to create infinite loops. 

Also making the watch sync to the changes are always reflected. 

If you think that's the better approach, you could sync it to the other two functions, otherwise I can do it later as well

**Comment by anteriovieira** [comment]
Thanks @antfu !  🙏🏽  The days have been busy for me and I let this one pass, it was a great learning experience for me.

And thanks @lishaobos for your help as well.

**Comment by anteriovieira** [comment]
@antfu should we introduce the improvement from #3168 here or keep the pull request? I agree that we shouldn't turn the value undefined if it equals the default value. And I think we don't need to trigger again if the value is the same. What do you think?

**Comment by antfu** [comment]
> @antfu should we introduce the improvement from #3168 here or keep the pull request? I agree that we shouldn't turn the value undefined if it equals the default value. And I think we don't need to trigger again if the value is the same. What do you think?

Yeah that make sense to me

**Comment by anteriovieira** [comment]
Hi @antfu , we've brought the other route-related tweaks into this pull request, can you take a look and let us know if we need to improve on anything?

**Review by antfu — APPROVED** [review]

**Pull request merged**
