### PR TITLE
feat(useMath): new function

### PR DESCRIPTION
**Pull request by FrankFang**
### Description

```ts
import { useMath } from '@vueuse/math'

const value = ref(45.95)
const rounded = useMath('round', value)
// rounded.value is 46
const floored = useMath('floor', value)
// floored.value is 45
```

### Additional context

https://github.com/vueuse/vueuse/issues/1812

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [x] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by zojize** [comment]
ideally, I'd love to use this function like this:

```ts
const {
  ceiled, // 43
  floored, // 42
  // better names?
  absed, // 42.42
  sqrted, // 6.513063795173513
  sign, // 1
} = useMath(42.42)
```

**Comment by antfu** [comment]
For reference: https://github.com/vueuse/vue-chemistry#usage

**Comment by FrankFang** [comment]
@antfu  你的意思是这样吗？

```ts
import {floor} from 'vuevue/math'

const {floor} = useMath()
const value1 = ref(1.1)
const result = floor(value1)
//result.value is 1
```

**Comment by FrankFang** [comment]
https://github.com/vueuse/vueuse/pull/1844 is better. close pr.

**Comment by FrankFang** [comment]
@zojize  It looks good, But it's a little strange that the type of result depends on the number of params:
```
const {floored} = useMath(1.1)
const {min} = useMath(1, 2)
```

**Comment by zojize** [comment]
> @zojize It looks good, But it's a little strange that the props of result depends on the number of params:
> 
> ```
> const {floored} = useMath(1.1) // no powed
> const {powed} = useMath(2, 2) // no floored
> ```

IMO in case of multiple arguments, it should be returned as a function.

e.g.
```ts
const { pow } = useMath(3)
const squared = pow(2) // ref(9)
const cubed = pow(3) // ref(27)
```

**Pull request closed without merging**
