### PR TITLE
feat(useVisible): implement useVisible functionality

### PR DESCRIPTION
**Pull request by Blackfaded**
### Description

Implementation of [this](https://github.com/vueuse/vueuse/issues/2345) proposal

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
How is this defer from `useElementVisibility`?

**Comment by Blackfaded** [comment]
`useElementVisibility` indicates if an element is inside the window or scrollTarget specified. It does not allow to set the visibility of an element.

This PR adds support for hiding an element, which has nothing to do with the viewport.

**Comment by antfu** [comment]
I am hesitant about:
- If the main usage is directive like `v-visible, it might be better to be provided as a separate package instead of in VueUse
- We should have a more distinguishable name compare to `useElementVisibility`

**Comment by Blackfaded** [comment]
Valid points. I always found the name `useElementVisibility` misleading, because it does not state the scope like the viewport. But changing this name would break backwars compatability, ao it is no option.


But how about the reverse approach:


`useHideElement`

`v-hidden`

`<Hidden :value="true" />`

?

**Pull request closed without merging**
