### PR TITLE
fix(useMagicKeys): handle meta key

### PR DESCRIPTION
**Pull request by shayneo**
This is an attempt to clean up the behavior noted in this issue: https://github.com/vueuse/vueuse/issues/915

### CODE REVIEW

**Comment by antfu** [comment]
I am not sure about the implementation, it feels a bit hacky and treats Meta too special. Do you know https://vueuse.org/core/useKeyModifier ? Maybe we could reuse this 🤔

**Comment by shayneo** [comment]
> I am not sure about the implementation, it feels a bit hacky and treats Meta too special. Do you know https://vueuse.org/core/useKeyModifier ? Maybe we could reuse it 🤔

yeah it definitely felt a little hackish while writing since meta is treated as such a special case. I'll take a look at `useKeyModifier` and see if there's a better way forward.

**Comment by rvmourik** [comment]
@shayneo Did you ever found a better solution? I am also running into the same problem as you mentioned.

**Comment by shayneo** [comment]
> @shayneo Did you ever found a better solution? I am also running into the same problem as you mentioned.

Hey @rvmourik , like Anthony mentioned, you might be able to use the `useKeyModifier` function to track the meta key properly in combination with `useMagicKeys`. Though I haven't attempted this yet.

If you get a working implementation, we should post here and perhaps add a note to the docs offering guidance on this case, as it seems common enough that folks will reach for `useMagicKeys` to implement `cmd+{whatever key}` shortcuts

**Comment by rvmourik** [comment]
> 

Hi @shayneo,

I tried it in combination with useKeyModifier, but the behaviour is the same in the end. The first time you try a combination with cmd + .. it works, but after releasing both keys, the event is only triggered by pressing the meta key and not the original combination.

Yeah, you find a lot of apps using the combination. But probably not with useMagicKeys :-) @antfu is there something that can be done to improve this implementation?

**Comment by ManuelLeiner** [comment]
I helped myself with something like the following using `onKeyDown`:

```
  onKeyDown("f", (e) => {
    if (e.metaKey) {
      e.preventDefault();
      search.value.focus();
    }
  });
```

**Comment by m0dch3n** [comment]
I'm also facing this issue...

@antfu Do you think the proposed pull request is something, which can soon be merged and published officially ? 

Since the request is pending since 4 month, I just wanted to know, if I should simply wait another few weeks, or if I should better create my own work around in the mean time?

**Comment by m0dch3n** [comment]
After having tried this commit, I noticed, it is still not working correctly, so I created myself a solution:

```javascript
import { computed, reactive, ref, unref } from 'vue'
import { noop } from '@vueuse/shared'
import {
  DefaultMagicKeysAliasMap,
  defaultWindow,
  MagicKeys,
  useEventListener,
  UseMagicKeysOptions,
} from '@vueuse/core'

/**
 * Reactive keys pressed state, with magical keys combination support.
 *
 * @see https://vueuse.org/useMagicKeys
 */
export function useMagicKeysCustomMetaHandling(
  options?: UseMagicKeysOptions<false>
): MagicKeys<false>
export function useMagicKeysCustomMetaHandling(
  options: UseMagicKeysOptions<true>
): MagicKeys<true>
export function useMagicKeysCustomMetaHandling(
  options: UseMagicKeysOptions<boolean> = {}
): any {
  const {
    reactive: useReactive = false,
    target = defaultWindow,
    aliasMap = DefaultMagicKeysAliasMap,
    passive = true,
    onEventFired = noop,
  } = options
  const current = reactive(new Set<string>())
  const toClean = new Set<string>()
  const obj = {
    toJSON() {
      return {}
    },
    current,
  }
  const refs: Record<string, any> = useReactive ? reactive(obj) : obj

  function updateRefs(e: KeyboardEvent, value: boolean) {
    const key = e.key?.toLowerCase()
    const code = e.code?.toLowerCase()
    const values = [code, key].filter(Boolean)

    // current set
    if (code) {
      if (value) {
        current.add(e.code)
        // track all the codes who were hit during together the metaKey
        if (e.metaKey) {
          toClean.add(e.code)
        }
      } else {
        current.delete(e.code)
        // clean all the tracked codes
        if (key === 'meta') {
          toClean.forEach((code) => current.delete(code))
          toClean.clear()
        }
      }
    }

    for (const key of values) {
      if (key in refs) {
        if (useReactive) refs[key] = value
        else refs[key].value = value
      }
    }
  }

  if (target) {
    useEventListener(
      target,
      'keydown',
      (e: KeyboardEvent) => {
        updateRefs(e, true)
        return onEventFired(e)
      },
      { passive }
    )
    useEventListener(
      target,
      'keyup',
      (e: KeyboardEvent) => {
        updateRefs(e, false)
        return onEventFired(e)
      },
      { passive }
    )
  }

  const proxy = new Proxy(refs, {
    get(target, prop, rec) {
      if (typeof prop !== 'string') return Reflect.get(target, prop, rec)

      prop = prop.toLowerCase()
      // alias
      if (prop in aliasMap) prop = aliasMap[prop]
      // create new tracking
      if (!(prop in refs)) {
        if (/[+_-]/.test(prop)) {
          const keys = prop.split(/[+_-]/g).map((i) => i.trim())
          refs[prop] = computed(() => keys.every((key) => unref(proxy[key])))
        } else {
          refs[prop] = ref(false)
        }
      }
      const r = Reflect.get(target, prop, rec)
      return useReactive ? unref(r) : r
    },
  })

  return proxy as any
}
```

This problem happens, because Mac OS is not firing the `keyup` event anymore, once the meta key is pressed. So basically a proper solution is NOT POSSIBLE.

What I basically do, do hack around:

I simply keep track in `const toClean = new Set<string>()` track of all the keys which were hit together during the meta keydown.

```javascript
    // current set
    if (code) {
      if (value) {
        current.add(e.code)
        // track all the codes who were hit during together the metaKey
        if (e.metaKey) {
          toClean.add(e.code)
        }
      } else {
        current.delete(e.code)
        // clean all the tracked codes
        if (key === 'meta') {
          toClean.forEach((code) => current.delete(code))
          toClean.clear()
        }
      }
    }
```

When the meta is then released, I clear all the keys from `current`

The only caveat: if the user is still holding the other key, it will delete it from `current`, and then a few ms later add it again, when key repeat of the holding fires the keydown event again.

In my app I don't need to solve this. However a possible solution would be:

```javascript
const toClean = new Map<string, number>()
...
toClean.add(e.code, new Date().getMilliseconds())
...
// on meta key release
// check if last hit is some time ago, then consider it's no longer pressed, and can safely be deleted 
```

**Comment by antfu** [comment]
#1312

**Pull request closed without merging**
