### PR TITLE
test: improve test coverage

### PR DESCRIPTION
**Pull request by sun0day**
### Description

All PRs from this branch intend to increase UT coverage and optimize vueuse source code. I will continuously commit test code to this branch. 

All commits in this branch are atomic, feel free to merge PR at any time.@antfu 

History PRs: 

- https://github.com/vueuse/vueuse/pull/2185
- https://github.com/vueuse/vueuse/pull/2233
- https://github.com/vueuse/vueuse/pull/2256
- https://github.com/vueuse/vueuse/pull/2300
- https://github.com/vueuse/vueuse/pull/2327

### Updated UT Coverage

|api|statements|branches|functions|lines
|-----|------|------|-----|-----|
|useTimeAgo|100% ⬆️|93.75% ⬆️  |100% ⬆️  |  100% ⬆️
|useChangeCase|100% ⬆️|100% ⬆️  |100% ⬆️  |  100% ⬆️
|useStorage|100% ⬆️|100% ⬆️  |100% ⬆️  |  100% ⬆️
|utils/compatibility|100% |100% ⬆️  |100%   |  100% 
|useAxios|100% ⬆️|100% ⬆️  |100% ⬆️  |  100% ⬆️

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Test

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by sun0day** [comment]
Is there a value type that is `Array` but not `object`? @sxzz @antfu 

https://github.com/vueuse/vueuse/blob/24747b636c61d23fa9c14474ba1a5ce78956dae1/packages/core/useStorage/guess.ts#L14-L17

**Comment by sxzz** [comment]
Hmmm, I think no. We could remove this checking.

**Comment by antfu** [comment]
@sun0day thanks for your continued contribution! Welcome to the team :)

**Comment by sun0day** [comment]
> @sun0day thanks for your continued contribution! Welcome to the team :)

It's my pleasure. 😄

**Pull request merged**
