### PR TITLE
feat(useDateFormat): support MMM and MMMM formatter

### PR DESCRIPTION
**Pull request by 777Vasya77**
### Description

Support `MMM` and  `MMMM` format. [#1641](https://github.com/vueuse/vueuse/issues/1641)

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [x] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by 777Vasya77** [comment]
@webfansplz, please check it

**Review by webfansplz — APPROVED** [review]

**Review by sxzz — APPROVED** [review]

**Comment by joshwcorbett** [comment]
I'm still encountering this issue after this PR, mainly using `MMM` or `MMMM` results in a 500 error despite being on version `9.2.0`

**Comment by 777Vasya77** [comment]
> I'm still encountering this issue after this PR, mainly using `MMM` or `MMMM` results in a 500 error despite being on version `9.2.0`

This PR is not included in version 9.2.0 [change log](https://github.com/vueuse/vueuse/releases/tag/v9.2.0)

**Comment by sxzz** [comment]
Haven't been released yet.
> The merge commit doesn’t appear in any tags

**Comment by joshwcorbett** [comment]
> > I'm still encountering this issue after this PR, mainly using `MMM` or `MMMM` results in a 500 error despite being on version `9.2.0`
> 
> 
> 
> This PR is not included in version 9.2.0 [change log](https://github.com/vueuse/vueuse/releases/tag/v9.2.0)

You're completely right, I assumed that it was already available given that the documentation has already been updated for it.

**Comment by 777Vasya77** [comment]
@joshwcorbett Pay attention to the section Changlog in the documentation, the status for the PR is indicated there [doc](https://vueuse.org/shared/usedateformat/#contributors)

**Pull request merged**
