### PR TITLE
docs: add support for client-side redirects for old functions paths

### LINKED ISSUE #4195: Doc: Official web page guide example url jump to error
### Describe the bug

Once I left-click the link in the popup page of hooks in the [examples](https://vueuse.org/guide/#usage-example), the result page is 404.
But if I right-click the link, and choose open in a new tab, it will bring me to the right page.

The same problems exist in all the example hooks popup links(usePreferredDark, useMouse, useLocalStorage)

image
image

### Reproduction

https://vueuse.org/guide/#usage-example

### System Info

```Shell
Microsoft Edge Version 128.0.2739.54 (Official build) (arm64)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by EvgenyWas**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

These changes add support for client-side redirects for old functions paths, for example, client navigation to `/useLocalStorage` will redirect to `/core/useLocalStorage`. However, this solution has a disadvantage in the screen blinking during navigation from the 404 page to the proper page. It might be avoided by rewriting all the old links in the functions' JSDoc.

Solution's reference: https://github.com/vuejs/vitepress/issues/4160

Resolves #4195

### Additional context

To test these changes locally you can change ` * @see https://vueuse.org/useLocalStorage` to `* @see [http://localhost:5173/useLocalStorage](http://localhost:5173/useLocalStorage)` on the line 15 in `packages\core\useLocalStorage\index.ts`.

### CODE REVIEW

**Comment by OrbisK** [comment]
Regardless of this prs, we could update the docstrings.

**Comment by EvgenyWas** [comment]
> Regardless of this prs, we could update the docstrings.

In this case, these changes are unnecessary. Would you like me to update the links in this PR instead of the current changes?

**Comment by OrbisK** [comment]
> > Regardless of this prs, we could update the docstrings.
> 
> In this case, these changes are unnecessary. Would you like me to update the links in this PR instead of the current changes?

If you want, you can do it. Otherwise I will :)

**Comment by EvgenyWas** [comment]
> If you want, you can do it. Otherwise I will :)
> 
> Open a new pr. Maybe this will be merged too.

Okay, thank you! I've opened another PR with links updates - https://github.com/vueuse/vueuse/pull/4447

**Comment by antfu** [comment]
This looks great, thanks!

**Comment by EvgenyWas** [comment]
> This looks great, thanks!

Thank you for the better solution!

**Pull request merged**
