### PR TITLE
docs(useDraggable): example for `preventDefault: true`

### LINKED ISSUE #3755: bug with useDraggable
### Describe the bug

when i use useDraggable with a img element, or a div inner with a img tag, the element is not draggable; you need to set the img tag attribute 'draggable' to false to resolve this bug;

### Reproduction

https://stackblitz.com/edit/vitejs-vite-wdwgnn/?file=src%2FApp.vue

### System Info

```Shell
chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by mnenie**
resolves #3755

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

So, in this issue, we have a problem related to the handling of img and without  `preventDefault: true`  in `options`  we should not have a moving an img. When we set the  `preventDefault: true`  in `options` its work great, but without this, we get a bug that is reproduced in  #3755

This pr resolves this bug

### CODE REVIEW

**Comment by antfu** [comment]
I am not so sure about the special handling for IMG - it might happend to the other elements as well. I think the best cases would be to have users enable the preventDefaults if they expect that behavior. I would see this is more like a documentation issue - we could improve the docs and guide users to use that options.

**Review by antfu — CHANGES_REQUESTED** [review]
As above

**Comment by mnenie** [comment]
> I am not so sure about the special handling for IMG - it might happend to the other elements as well. I think the best cases would be to have users enable the preventDefaults if they expect that behavior. I would see this is more like a documentation issue - we could improve the docs and guide users to use that options.

yea maybe you're right, I'll do it 😉

**Comment by mnenie** [comment]
> As above

@antfu check please, I've added edits to the documentation. I hope this is what we need 😉💯

**Pull request merged**
