### PR TITLE
feat(useVModel): new  component

### PR DESCRIPTION
**Pull request by howold-lab**
### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ ] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
I am not sure if I understand the usage of this. Can you explain a bit?

**Comment by michael-observerly** [comment]
@antfu Agree, @howold-lab could you provide some description with this please. It seems like this is a component example for the usage documentation with useVModel...

**Comment by howold-lab** [comment]
@antfu @michael-observerly I wanted to make people understand more about what useModel does, so I made a simple component display to show usrModel

**Comment by wheatjs** [comment]
Sorry I don't think this function fits the component architecture very well. The implementation might be a bit too specific as well. Going to close for now. Thanks for your contribution though!

**Pull request closed without merging**
