### PR TITLE
feat(usePerformanceObserver): new function

### PR DESCRIPTION
**Pull request by LockingReal**
提交获取当前页面常见性能指标参数的hook

### Additional context

---

### What is the purpose of this pull request? 

- [X ] Bug fix
- [ √] New Feature
- [ X] Documentation update
- [ X] Other

### Before submitting the PR, please make sure you do the following

- [√ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ √] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [ √] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ √] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ √] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by vaakian** [comment]
直接用 reactive 包裹 `performance.timing` 对象应该是不行的，你可能需要 [PerformanceObserver](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver) 来实现响应式。

**Comment by LockingReal** [comment]
> 直接用 reactive 包裹 `performance.timing` 对象应该是不行的，你可能需要 [PerformanceObserver](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver) 来实现响应式。

ok，感谢感谢，我这看着改一下

**Comment by LockingReal** [comment]
>老哥，我又提交了一个版本，算是wip，麻烦帮忙看一下，这个思路写下去是对的不，感谢感谢 @vaakian

**Comment by okxiaoliang4** [comment]
@LockingReal I created a PR in your repo, I think we should keep the feature simple to focus the one thing. other feature can wrapper it.

https://github.com/LockingReal/vueuse/pull/1

**Review by okxiaoliang4 — DISMISSED** [review]

**Review by antfu — APPROVED** [review]

**Pull request merged**
