### PR TITLE
feat(useExpiringRef): new function

### PR DESCRIPTION
**Pull request by silberGuy**
### Description

solves #2410

### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
How would it differencing from https://vueuse.org/shared/refautoreset/#refautoreset?

**Comment by silberGuy** [comment]
> How would it differencing from https://vueuse.org/shared/refautoreset/#refautoreset?

Thank you for the response, I did not find this previously but it really the same as `useExpiringRef`, except for the ability to update the timeout after creation
Also `useAsyncExpiringRef` creates an auto-reseting ref that defaults to an async value from a function

**Comment by antfu** [comment]
> except for the ability to update the timeout after creation

Well actually you can:

```ts
const timeout = ref(100)
const foo = refAutoReset('foo', timeout)

// change the timeout
timeout.value = 200
```

**Comment by antfu** [comment]
Thanks for your contribution. I think introducing two similar functions with only subtle different would cause the confusion and increase the maintenance burden. It would be better to improve the existing one if you see something really missing. Thanks

**Pull request closed without merging**
