### PR TITLE
feat(useMath): add useMath and types

### PR DESCRIPTION
**Pull request by TwoKe945**
### Description
```ts
import { useMath } from '@vueuse/math'

const value = ref(45.95)
// useMath: (methodName: 'round', arg_0: MaybeComputedRef<number>) => ComputedRef<number>
const rounded = useMath('round', value)
// rounded.value is 46

// useMath: (methodName: 'floor', arg_0: MaybeComputedRef<number>) => ComputedRef<number>
const floored = useMath('floor', value)
// floored.value is 45

// useMath: (methodName: 'max',  ...args: MaybeComputedRef<number>) => ComputedRef<number>
const maxed = useMath('max',  1, 2,3)
// maxed .value is 3
```

### Additional context

基于 [#1842](https://github.com/vueuse/vueuse/issues/1841) 添加参数类型以及返回值类型

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [x] Documentation update
- [x] Other

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ ] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by FrankFang** [comment]
https://github.com/vueuse/vueuse/pull/1841#issuecomment-1181222457

**Comment by FrankFang** [comment]
good job.

**Comment by TwoKe945** [comment]
测试结果
```ts
import { ref } from 'vue-demi'
import { useMath } from './useMath'

describe('useMath2', () => {
  it('should be defined', () => {
    const methods = useMath()
    // expect(useMath).toBeDefined()
    expect(methods).toMatchInlineSnapshot(`
      {
        "abs": [Function],
        "acos": [Function],
        "acosh": [Function],
        "asin": [Function],
        "asinh": [Function],
        "atan": [Function],
        "atan2": [Function],
        "atanh": [Function],
        "cbrt": [Function],
        "ceil": [Function],
        "clz32": [Function],
        "cos": [Function],
        "cosh": [Function],
        "exp": [Function],
        "expm1": [Function],
        "floor": [Function],
        "fround": [Function],
        "hypot": [Function],
        "imul": [Function],
        "log": [Function],
        "log10": [Function],
        "log1p": [Function],
        "log2": [Function],
        "max": [Function],
        "min": [Function],
        "pow": [Function],
        "random": [Function],
        "round": [Function],
        "sign": [Function],
        "sin": [Function],
        "sinh": [Function],
        "sqrt": [Function],
        "tan": [Function],
        "tanh": [Function],
        "trunc": [Function],
      }
    `)
  })
  it('should accept max', () => {
    const value1 = ref(10)
    const value2 = ref(20)
    const { max } = useMath()
    const result = max(value1, value2, 100, 4, 5)
    expect(result.value).toMatchInlineSnapshot('100')
    value1.value = 300
    expect(result.value).toMatchInlineSnapshot('300')
  })
  it('should accept min', () => {
    const value1 = ref(10)
    const value2 = ref(20)
    const { min } = useMath()
    const result = min(value1, value2, 5, 300)
    expect(result.value).toMatchInlineSnapshot('5')
    value2.value = 2
    expect(result.value).toMatchInlineSnapshot('2')
  })
  it('should accept floor', () => {
    const value1 = ref(1.1)
    const { floor } = useMath()
    const result = floor(value1)
    expect(result.value).toMatchInlineSnapshot('1')
    value1.value = 5.2
    expect(result.value).toMatchInlineSnapshot('5')
  })
  it('should accept round', () => {
    const value1 = ref(4.5)
    const { round } = useMath()
    const result = round(value1)
    expect(result.value).toMatchInlineSnapshot('5')
    value1.value = 5.2
    expect(result.value).toMatchInlineSnapshot('5')
  })
  it('should accept pow', () => {
    const value1 = ref(4)
    const { pow } = useMath()
    const result = pow(value1, 2)
    expect(result.value).toMatchInlineSnapshot('16')
    value1.value = 5
    expect(result.value).toMatchInlineSnapshot('25')
  })
})
```

**Comment by antfu** [comment]
Well, we have `reactifyObject(Math)` 😅 https://vueuse.org/shared/reactifyobject/

**Comment by TwoKe945** [comment]
😅😅

**Pull request closed without merging**
