### PR TITLE
fix(useElementByPoint): fix ssr

### PR DESCRIPTION
**Pull request by okxiaoliang4**

### CODE REVIEW

**Comment by wheatjs** [comment]
Is this actually broken? I believe `useRafFn` will only run on the client

**Comment by okxiaoliang4** [comment]
Try to access it directly, there will be exceptions [useElementByPoint](https://vueuse.org/core/useelementbypoint/)

```typescript
  // useRafFn
  function loop() {
    if (!isActive.value)
      return
    fn() // will throw a execption
    if (window)
      window.requestAnimationFrame(loop)
  }
```

**Comment by wheatjs** [comment]
Hmm, guess so

**Comment by antfu** [comment]
We could fix it in useRaf instead

**Pull request closed without merging**
