### PR TITLE
fix(useScrollLock): fix iOS touchmove bug

### PR DESCRIPTION
**Pull request by robinscholz**
### Description

This PR solves iOS touchmove issues that prevent any children elements of the locked element from scrolling. I believe this will solve #2278.

### Additional context

I believe there are no breaking changes, however it'd be good to confirm this with a few different devices.

---

### What is the purpose of this pull request? 

- [X] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by robinscholz** [comment]
Not sure why the test is failing, should have nothing to do with the proposed changes

**Review by webfansplz — DISMISSED** [review]

**Comment by robinscholz** [comment]
@webfansplz After some more tests I ran into problems with my original solution. I believe the only way to truly solve this is by checking for `overflow: scroll` within the `event.target` and its’ parentNodes. 

Caveat is that the user needs to explicitly set the overflow to scroll to keep elements scrollable on iOS.

**Comment by robinscholz** [comment]
@antfu would be happy to get your opinion on this implementation!

**Review by dpschen — DISMISSED** [review]

**Comment by David-Tsui** [comment]
@robinscholz This problem still exists at `9.10.0`, test by IOS devices in chrome emulator. I found a way to fix is removing the touchmove event listener added to IOS.

**Pull request merged**
