### PR TITLE
fix(useTimeAgo): Support custom UnitNames type for units field

### PR DESCRIPTION
**Pull request by nickmessing**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

At the moment typescript complains if we use non-default units in the `units` field for `useTimeAgo` (or `formatTimeAgo`) options. I assume this was just overlooked and not many people actually use custom units.

### CODE REVIEW

**Review by Doctor-wu — DISMISSED** [review]

**Comment by nickmessing** [comment]
@Doctor-wu tests are failing, let me check it out.

**Comment by nickmessing** [comment]
@Doctor-wu, Fixed the types properly (this time in an actual IDE 😅). But locally a test related to `computedEager` is failing, I don't think my PR has anything to do with that so I'm leaving it as-is.

**Comment by Doctor-wu** [comment]
> @Doctor-wu, Fixed the types properly (this time in an actual IDE 😅). But locally a test related to `computedEager` is failing, I don't think my PR has anything to do with that so I'm leaving it as-is.

That's a known issue and had been fixed in`main`, you can update your local branch

**Comment by Doctor-wu** [comment]
Test passed, thanks for your contribution @nickmessing

**Review by Doctor-wu — APPROVED** [review]

**Pull request merged**
