### PR TITLE
feat(useElementHover): support multiple target

### PR DESCRIPTION
**Pull request by Dunqing**
### Description

Support multiple EventTarget

### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Review by sxzz — COMMENTED** [review]
First of all, it will cause a breaking change.

Also, I don't think this feature is necessary, please let each function be simple and have only one main feature, then you can compose them.

For example, you can write this function by `useElementHover` and [`logicOr`](https://vueuse.org/math/logicOr) by yourself.

**Comment by Dunqing** [comment]
Thank for your review!

> First of all, it will cause a breaking change.

I don't think so, it still supports non-arrays.

> 
> Also, I don't think this feature is necessary, please let each function be simple and have only one main feature, then you can compose them.

This would actually be useful in a dropdown and popover component, making it support array targets would reduce duplicate code

> For example, you can write this function by `useElementHover` and [`logicOr`](https://vueuse.org/math/logicOr) by yourself.

Thanks! Let me see how I can simplify this logic.

**Comment by antfu** [comment]
I don't think the complexity is necessary here, while you can simply call it multiple times when needed. We don't have such a convention to support multiple targets, and this will cause users to ship extra code even if they don't need it. Thanks but I'd reject this.

**Pull request closed without merging**
