### PR TITLE
feat(add,subtract,multiply,divide): new functions

### PR DESCRIPTION
**Pull request by wheatjs**
Reactive operators for addition, subtraction, multiplication, and division.

Sometimes when using composable you will need to do basic operations such as addition. This can make simple things a bit more verbose, for example this https://github.com/vueuse/vueuse/issues/1014#issuecomment-986530188 could be simplified to

```html
<script setup lang="ts">
...

const restrictedX = useClamp(left.value, x.value, subtract(right.value, width.value))
const restrictedY = useClamp(top.value, y.value, subtract(bottom.value, height.value))
</script>
```
Not having to create a computed for simple arithmetic is pretty convenient I think, but I'm not really sure if this is a great idea, so I'd like some feedback.

cc @antfu @patak-dev

### CODE REVIEW

**Comment by antfu** [comment]
The naming sounds a bit too general, how about `numericAdd`, `numericDivide` etc?

**Comment by wheatjs** [comment]
Hmm are you thinking it might conflict with other functions is users codebases or that the naming might confuse people?

**Comment by patak-dev** [comment]
Interesting. Maybe under an object like `reactive.add()`?

At one point I thought that we wouldn't use ref sugar in a library like VueUse, but I think that it may actually make the code a lot more maintainable in some of the composables. Maybe we should push for that?

```js
import { useDraggable, useElementBounding, clamp } from '@vueuse/core';

const container = $ref();
const draggable = $ref();

const { left, right, top, bottom } = $(useElementBounding(container));
const { width, height } = $(useElementBounding(draggable));
const { x, y } = $(useDraggable(draggable));

const restrictedX = $computed(() => clamp(left, x, right - width));
const restrictedY = $computed(() => clamp(top, y, bottom - height));
```

**Comment by wheatjs** [comment]
I do think that the syntax sugar can help, but there are still situations where it might be not be useful. For instance if we have a function that take a ref number as a parameter, we would have to have a computed to use that. Like `useClamp` for example, I think it might not be unusual to have one of the parameters be something the user will need to calculate. To me having something like `add`, etc, would be much more "composable" then using a computed with a generic clamp function. Maybe I'm incorrect in this thinking though. 

To me though something like 
```ts
const x = useClamp(...)
``` 
is much more clear in an initial scanning of the code that `x` is a clamped value than something like 
```ts
const x = computed(() => clamp(...))
```

**Comment by michael-observerly** [comment]
> The naming sounds a bit too general, how about `numericAdd`, `numericDivide` etc?

I feel like add, subtract, multiply and divide as a set are self-explanatory ... do we apply these mathematical operations to any other type other than number?

**Comment by antfu** [comment]
Btw, you might want to try this
https://github.com/vueuse/vue-chemistry

**Comment by antfu** [comment]
On a second thought, I think it's better to have them live in vue-chemistry.

**Pull request closed without merging**
