### PR TITLE
fix(useElementVisibility): adjust threshold to 0 to fix visibility issue with large element

### PR DESCRIPTION
**Pull request by erikkkwu**
…sue with large element

### Before submitting the PR, please make sure you do the following

- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [X] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

fix https://github.com/vueuse/vueuse/issues/3305https://github.com/vueuse/vueuse/issues/3305
large element cause intersectionRatio to fall below the default threshold 0.1, making elementIsVisible false (e.g., viewport height 900 / target height  9001).

### Additional context

---

### <samp>🤖 Generated by Copilot at 65d7dfa</samp>

Added `threshold` option to `useElementVisibility` hook to support elements with zero dimensions. This option controls how much of the element's area needs to be visible before the hook reports it as visible.

### <samp>🤖 Generated by Copilot at 65d7dfa</samp>

* Add `threshold` option to `IntersectionObserver` constructor to detect visibility of zero-sized elements ([link](https://github.com/vueuse/vueuse/pull/3308/files?diff=unified&w=0#diff-a0e7183f844c148d0741a2fe6103bd256910d9ffc85e441de996f9e4d37d3151R33))

### CODE REVIEW

**Review by samuveth — APPROVED** [review]
tACK

**Review by antfu — APPROVED** [review]

**Comment by rikzwarthoff** [comment]
@erikkkwu @antfu @samuveth, Hi guys, this parameter is now hard coded, whilst it should be passed through as an option imo. We've had issues with 0 threshold, I actually need it to be 0.1

**Comment by edtorba** [comment]
> @erikkkwu @antfu @samuveth, Hi guys, this parameter is now hard coded, whilst it should be passed through as an option imo. We've had issues with 0 threshold, I actually need it to be 0.1

I had the exact same issue. As a workaround, I moved to using `useIntersectionObserver`. However, I am considering spinning up a PR to allow its definition via an option.

**Comment by erikkkwu** [comment]
Hello @rikzwarthoff @edtorba, I would like to inquire about the specific situations in which you encounter issues. Indeed, if you do face problems, I agree that it should be possible to turn it into an option

**Comment by rikzwarthoff** [comment]
Hi @erikkkwu, we have the following situation. A `div` wrapped around a `table`, which has multiple `tbody` elements, each of those `tbody` elements has a `useElementVisibility` where the `scrollTarget` is the `div`. Now the table has an after element with calculated height so you can always scroll the last `tbody` to the top. The first row of each tbody is sticky, my guess that the problem would the there.

I can dm the url if you would want it.

**Pull request merged**
