### PR TITLE
feat:(useLoading):new fucntion

### PR DESCRIPTION
**Pull request by macheteHot**
use case
```js
const [isLoading, useThisFn] = useLoadingFn(async() => {
  // await  some thing
})
```

### CODE REVIEW

**Comment by wheatjs** [comment]
Seems like a duplicate of https://vueuse.org/core/useasyncstate/

**Comment by macheteHot** [comment]
ohhh my bad.🤣

**Comment by macheteHot** [comment]
Is not same like useasyncstate
when you call new function  will automatically toggle boolean `isLoading` usually use to  waiting status like waiting button , waiting some fetch

**Comment by wheatjs** [comment]
Wouldn't it be functionally the same as

```ts
const { state, isReady, execute } = useAsyncState((args) => sleep(5000),
  {},
  { immediate: false },
)
```
You can then use `execute` as the instead of `useThisFn`

**Comment by macheteHot** [comment]
Is not same  
use loading first time toggle `isLoading` value 
wd66o-idw03

**Comment by wheatjs** [comment]
Seems to me that isLoading is just the inverted state of isReady. Is there any other difference besides that?

**Comment by macheteHot** [comment]
When the function finishes executing  `isReady` is aways be true unless re-run 
if the button bind `isReady` to loading prop  will block the run

isReady => true => false 

isLoading => false => true => false

**Comment by wheatjs** [comment]
Ah well if that is the case, then I suggest we add an `isLoading` property to `useAsyncState` instead

**Comment by macheteHot** [comment]
> Ah well if that is the case, then I suggest we add an `isLoading` property to `useAsyncState` instead

This is a brilliant idea

**Pull request closed without merging**
