### PR TITLE
fix: useStorage sync race condition, closes #808

### LINKED ISSUE #808: Bug: useStorage
## useStorage bug(maybe?)
- open opening a new window will loop indefinitely.
- Crazy jitter!!! and 
- I think there are two instances created, but both are responsive, and both are constantly responding.
I can't send a gif
please try this=>

image

### PR DESCRIPTION
**Pull request by Akryum**
### Description

closes #808

### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
Haha, you are a live saver!

**Comment by antfu** [comment]
The test failed. I made the change 27d1ba2a but not user if it's a complete fix

**Comment by Akryum** [comment]
Sorry, should have put the PR in draft :bow:

**Comment by Akryum** [comment]
I checked on https://vue3.examples.histoire.dev/ and I no longer see the resizing of the responsive view glitching with several tabs open.

**Pull request merged**
