### PR TITLE
feat(tryOnMounted): support target arguement

### PR DESCRIPTION
**Pull request by tolking**
### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ ] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

When using tryOnMounted in some special cases, a vue error will be triggered. Avoiding this error by adding target attributes.

### Additional context

---

### <samp>🤖 Generated by Copilot at 692eb53</samp>

Pass the current instance as the second argument to the `onBeforeMount`, `onBeforeUnmount`, `onMounted`, and `onUnmounted` hooks in the `tryOn*` functions. This fixes a bug where the hooks could be registered on the wrong component instance in some cases.

### <samp>🤖 Generated by Copilot at 692eb53</samp>

*  Pass the current instance as the second argument to the lifecycle hooks in `tryOnBeforeMount`, `tryOnBeforeUnmount`, `tryOnMounted`, and `tryOnUnmounted` functions to ensure the hooks are registered on the correct component instance in scenarios such as async setup or suspense ([link](https://github.com/vueuse/vueuse/pull/3185/files?diff=unified&w=0#diff-8c7c52531b6717364d2356a58d74dd0ef2acc57c6e9829de5cad7ec2f60a532bL11-R13), [link](https://github.com/vueuse/vueuse/pull/3185/files?diff=unified&w=0#diff-1b9fdb6c25ef02223f4c77a0350d1d5ab7f6f35d024db23065ec696f3d87de84L10-R12), [link](https://github.com/vueuse/vueuse/pull/3185/files?diff=unified&w=0#diff-3691020f3408a5f82e4130b6a9bf0fb82d342f55f4f9d3bf5b089d40c85bfb91L12-R14), [link](https://github.com/vueuse/vueuse/pull/3185/files?diff=unified&w=0#diff-7fd96c603d65e35c2a9c084fd40fec76b3c984d9ae64370ea2995f750befb3a8L11-R13))

### CODE REVIEW

**Comment by antfu** [comment]
Can you provide more details, ideally a reproduction, of why that would cause errors? I think those hooks automatically infer the instance from getCurrentInstance, and we don't need to do this.

**Comment by tolking** [comment]
[Demo](https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHjMYACKmIFFKGwAvAAdEAzbAB+CFgB8z2F0iIdC1dWkKmAKix6dSVEYKmsRk7SGk4s41hVAElsMhpBBbGkDjUOLMVAByBYL-NZescRvN6QcEIAeWwAFl2CqQSoZ0Y53hFw6bpy6ogV9hV8Xxy35KWVLm31qAiDtNpHFzcsm1XFQ3zHRswATbhdClGh6i-PEAAVoMQWCDHggDV1ArtEGkThzGAHCwKg6A0LgxAODQFRSJgiiOCjQxyBwg5VwOexsJLfhZVFfwbhQsj0MwxwiPMcDXzMcdJ24T8VD7AcOCHaRRykqcsLEl9INQoTKNk7ttAXBcOKfDT5DYINJi8eADMkicpwXTtbOkxBjLAnDtz3Q9j3bf9AOA0SwJI7T6MYgxVC-BdiUadoABYAFZHzA9jOLA6x8I4cxaPIjDKLY1dGQOA4gA)

**Comment by antfu** [comment]
1. You should not create composables in computed functions. I think it's a bit anti-pattern.
2. If we are going to support manual instance, I think our `tryOnXXX` functions should also support an instance argument and pass through,

**Review by antfu — DISMISSED** [review]

**Comment by antfu** [comment]
It seems to break the Vue 2 tests

**Comment by tolking** [comment]
I'll take some time to take a look

**Pull request merged**
