### PR TITLE
feat(toValueDeep): new function

### LINKED ISSUE #3190: ✨ new composable `toValueDeep`
### Clear and concise description of the problem

Hi 👋🏻 

We are aware of `toValue` inroduced in vue 3.3 but this doesn't work for nested object. assume toValue for nested ref:
```ts
const x = { a: ref(1) }

toValue(x) // { a: ref(1) }

toValueDeep(x) // { a: 1 }
``` 

Other examples are:
```ts
const x = ref({ a: ref(1), b: { c: ref(2) } })
const y = ref([{ a: ref(1) }, { a: ref(2) }])
const x = [{ a: ref(1) }, { a: ref(2) }]
```

### Suggested solution

N/A

### Alternative

N/A

### Additional context

I was working on this composable but typescript is hard when it comes to recursion & looping 😅 

Here's my rough implementation if someone want to work further:
```ts
const toValueDeep = <T>(value: MaybeRefOrGetter<T>): T => {
  const _val = toValue(value)

  if (isRef(_val))
    return toValueDeep(_val)
  else if (Array.isArray(_val))
    return _val.map(toValueDeep)
  else if (typeof _val === 'object' && _val !== null)
    return Object.fromEntries(
      Object.entries(_val)
        .map(
          ([k, v]) => [k, toValueDeep(v)],
        ),
    )

  return _val
}
```

<details>
<summary>Once we have this I'll try to give new PR for new composable `useUrl`</summary>

```ts
const postId = ref(1)
useUrl('https://jsonplaceholder.typicode.com/posts/{postId}/comments', {
  query: { q: 'ticket' },
  params: { postId },
})
// returns => https://jsonplaceholder.typicode.com/posts/1/comments?q=ticket
```

This will be super useful for useFetch as current useFetch isn't provide way to pass `query` via object and we have to create additional computed property for this.

</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by jd-solanki**
closes #3190

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

I'm implmenting `query` support in `useFetch` composable in [this](https://github.com/vueuse/vueuse/pull/3191) PR. For useQuery to support various ref type and extract easily we need this composable to get the deep value.

### Additional context

Thanks @Alfred-Skyblue for implementing the type for this composable

---

### <samp>🤖 Generated by Copilot at 79b1ba7</samp>

This pull request adds a new function `toValueDeep` to the `shared` package, which can unwrap any nested refs in a reactive value. It also includes the documentation and tests for the function.

### <samp>🤖 Generated by Copilot at 79b1ba7</samp>

*  Export and document `toValueDeep` function, which recursively unwraps refs in nested structures ([link](https://github.com/vueuse/vueuse/pull/3213/files?diff=unified&w=0#diff-4ef755f3c945daaa416774a88556b30166725160cf2ce87e21ed80aca4ffd115R28), [link](https://github.com/vueuse/vueuse/pull/3213/files?diff=unified&w=0#diff-8e1d6bbc07356b3a9f50cb42d3233f749ecd595643e116c59445a1f4ccace624R1-R23))
* Implement `toValueDeep` function in `packages/shared/toValueDeep/index.ts`, using `vue-demi` and `toValue` helper ([link](https://github.com/vueuse/vueuse/pull/3213/files?diff=unified&w=0#diff-8014ed6a9bd2d919917ecb7bf012c60137b20311112c3eb6824687ad43e785d0R1-R30))
* Add unit tests for `toValueDeep` function in `packages/shared/toValueDeep/index.test.ts`, using `vitest` and `JSON.stringify` ([link](https://github.com/vueuse/vueuse/pull/3213/files?diff=unified&w=0#diff-a668cc58efbfd3b60e9017221e7b8ec55ffffcdf056eebb41596ed407f6d363fR1-R49))

### CODE REVIEW

**Comment by Alfred-Skyblue** [comment]
I think the performance is not very good, it recursively implements the toValue of object and array.

**Comment by jd-solanki** [comment]
Sorry @Alfred-Skyblue I'm limited to this according to my knowledge. Feel free to take over this PR if you are aware of any performance boost, I'll wait as I can't proceed further for #3191 😅 .

**Comment by Alfred-Skyblue** [comment]
You can return a Proxy and perform toValueDeep in get, so that the depth conversion will only be performed when getting.

**Comment by jd-solanki** [comment]
> You can return a Proxy and perform toValueDeep in get, so that the depth conversion will only be performed when getting

What if we pass its value somewhere? 🤔 

```ts
const q = ref('')
new URLSearchParams(toValueDeep({ q }))
```

**Comment by Alfred-Skyblue** [comment]
Refer to reactive in vue.

**Comment by jd-solanki** [comment]
While exploring the reactive I came up with this: `toValue(reactive(val))`. I also implemented this in the #3191 and it's working as expected.

I guess there's no need for this composable if we use above mentioned trick. What's your thoughs?

> _P.S. Feel free to close this_

**Pull request closed without merging**
