### PR TITLE
refactor(useAxios): refactor `AxiosRequestConfig` type

### PR DESCRIPTION
**Pull request by jahnli**
ref https://github.com/axios/axios/pull/5486

https://github.com/axios/axios/releases/tag/v1.2.4

axios has dropped the `RawAxiosRequestConfig` renaming back to `AxiosRequestConfig`

### CODE REVIEW

**Comment by webfansplz** [comment]
Be related to #2662 #2666

**Comment by jahnli** [comment]
@webfansplz    You mentioned these changes in axios1.2.3. In 1.2.4, these changes have been rolled back

**Comment by jahnli** [comment]
@webfansplz  
image

**Comment by webfansplz** [comment]
Yes, I know. I mentioned them just to provide context.Let's also update `axios` to v1.2.4

**Comment by jahnli** [comment]
ok ,  axios latest version 1.2.5

**Comment by vaakian** [comment]
you should run `pnpm update -r axios` and push the version changes here, so as to satisfy the type check.

**Comment by jahnli** [comment]
@vaakian  It's OK

**Comment by antfu** [comment]
Can you help resolve the conflicts? Thanks

**Comment by jahnli** [comment]
@antfu  It's ok

**Comment by jahnli** [comment]
@antfu  please confirm

**Pull request merged**
