### PR TITLE
chore(docs): dynamic functions count

### PR DESCRIPTION
**Pull request by webfansplz**
### Description

image

image

### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [x] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
Not sure, how do you deal with GitHub's readme?

**Comment by webfansplz** [comment]
> Not sure, how do you deal with GitHub's readme?

I don't really understand ，Do you mean here :
https://github.com/vueuse/vueuse/blob/53d198375359e049ae646b441bddd967d50b1b12/scripts/utils.ts#L278

**Comment by antfu** [comment]
The badge is not only used on the website but also the README page on GitHub https://github.com/vueuse/vueuse , which I don't think it's possible to dynamic without a server

**Comment by webfansplz** [comment]
> The badge is not only used on the website but also the README page on GitHub https://github.com/vueuse/vueuse , which I don't think it's possible to dynamic without a server

I know，we has already deal with it via https://github.com/vueuse/vueuse/blob/53d198375359e049ae646b441bddd967d50b1b12/scripts/utils.ts#L278

Maybe there is something wrong with my description, the solution is just to read the number of functions when we run the update command.

**Comment by antfu** [comment]
I made the badge generated on the build time and serve with our docs: https://vueuse.org/badge-function-count.svg this way we could make both of them dynamic and make PRs cleaner. Thanks for the initiator

**Pull request closed without merging**
