### PR TITLE
feat(useComputedRef): add useComputed ref

### PR DESCRIPTION
**Pull request by Kingwl**

### CODE REVIEW

**Comment by lsdsjy** [comment]
It seems that `eagerComputed` solves the same problem:
https://vueuse.org/shared/eagercomputed/

**Comment by Kingwl** [comment]
Shit. yes.

**Comment by Kingwl** [comment]
> It seems that `eagerComputed` solves the same problem: https://vueuse.org/shared/eagercomputed/

@lsdsjy 

It's actually not. [For example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcmVhZG9ubHksIGNvbXB1dGVkLCB3YXRjaCwgc2hhbGxvd1JlZiwgd2F0Y2hTeW5jRWZmZWN0LCBvblVwZGF0ZWQgfSBmcm9tICd2dWUnXG5cbmZ1bmN0aW9uIGVhZ2VyQ29tcHV0ZWQoZm4pIHtcbiAgY29uc3QgcmVzdWx0ID0gc2hhbGxvd1JlZigpXG5cbiAgd2F0Y2hTeW5jRWZmZWN0KCgpID0+IHtcbiAgICByZXN1bHQudmFsdWUgPSBmbigpXG4gIH0pXG5cbiAgcmV0dXJuIHJlYWRvbmx5KHJlc3VsdClcbn1cbiAgXG5mdW5jdGlvbiB1c2VDb21wdXRlZFJlZihnZXR0ZXIsIHdhdGNoT3B0aW9ucykge1xuICBjb25zdCBjb21wdXRlZFZhbHVlID0gY29tcHV0ZWQoZ2V0dGVyKVxuXG4gIGNvbnN0IHJlZlZhbHVlID0gcmVmKGNvbXB1dGVkVmFsdWUudmFsdWUpXG4gIHdhdGNoKCgpID0+IGNvbXB1dGVkVmFsdWUudmFsdWUsICh2YWx1ZSkgPT4ge1xuICAgIHJlZlZhbHVlLnZhbHVlID0gdmFsdWVcbiAgfSwgd2F0Y2hPcHRpb25zKVxuXG4gIHJldHVybiByZWZWYWx1ZVxufVxuXG5jb25zdCB2ID0gcmVmKDEpXG5jb25zdCB2diA9IHJlZigxKVxuc2V0SW50ZXJ2YWwoKCkgPT4ge1xuICB2LnZhbHVlKytcbiAgdnYudmFsdWUrK1xufSwgMzAwKVxuICBcbmNvbnN0IGlzT2RkID0gdXNlQ29tcHV0ZWRSZWYoKCkgPT4ge1xuICByZXR1cm4gKHYudmFsdWUgKyB2di52YWx1ZSkgJSAyICE9PSAwXG59KVxuXG4vL2NvbnN0IGlzT2RkID0gZWFnZXJDb21wdXRlZCgoKSA9PiB7XG4vLyAgcmV0dXJuICh2LnZhbHVlICsgdnYudmFsdWUpICUgMiAhPT0gMFxuLy99KVxuXG5vblVwZGF0ZWQoKCkgPT4ge1xuICBjb25zb2xlLmxvZygndXBkYXRlJylcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgaXNPZGQgfX08L2gxPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=), `eagerComputed ` will not avoid the render, but the `useComputedRef ` will be.

**Comment by Kingwl** [comment]
@lsdsjy 
I think extend the `eagerComputed` is a good choose. https://github.com/vueuse/vueuse/pull/1192

**Pull request closed without merging**
