### PR TITLE
fix(useElementSize): fix incorrect element size on SVG

### PR DESCRIPTION
**Pull request by Lionad-Morotar**
### Description

fix [#2084](https://github.com/vueuse/vueuse/issues/2084)

fix incorrect size on SVG element, due to https://www.w3.org/TR/resize-observer/#calculate-box-size

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Review by wheatjs — COMMENTED** [review]
Looks good to me unless anyone thinks this will introduce some breaking changes, but I can't see any obvious ones.

**Comment by MstrVLT** [comment]
https://github.com/vueuse/vueuse/blob/da0d7263db5f0cb8a83bfb80c6ad09e1813542ee/packages/core/useElementSize/index.ts#L27
Method isSVG check only svg tag. What about the g tag? 
Ex: I am building inside svg -> d chart and want to center align using translate (svg width 100%)

**Comment by Lionad-Morotar** [comment]
> https://github.com/vueuse/vueuse/blob/da0d7263db5f0cb8a83bfb80c6ad09e1813542ee/packages/core/useElementSize/index.ts#L27
> 
> 
> Method isSVG check only svg tag. What about the g tag?
> Ex: I am building inside svg -> d chart and want to center align using translate (svg width 100%)

It seems works fine with "g" tag:

image

g、path 等标签也支持。不过，我觉得 getComputedStyle 这个方法也许换成 getBoundingRect 会更好一些？

**Comment by MstrVLT** [comment]
> getComputedStyle

that was the problem - thx!

**Pull request merged**
