### PR TITLE
keepAliveScope

### PR DESCRIPTION
**Pull request by sabereen**
#### keepAliveScope
Creates a [effectScope](https://vuejs.org/api/reactivity-advanced.html#effectscope) that is disposed when the component is deactivated.

We can disable composable functions that are not needed in deactivated state of "KeepAlive".

```js
import { keepAliveScope, useEventListener } from '@vueuse/core'

keepAliveScope(() => {
  // listen to scroll event only if the component is not deacivated
  useEventListener('scroll', () => {
    // ...
  })
})
```

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
Sounds like good ideas. Can you split them into two separate PRs so we can discuss the improvements we could make separately? Thank you

**Comment by sabereen** [comment]
I removed one of them and will make another PR for that one.

**Comment by sabereen** [comment]
https://github.com/vueuse/vueuse/pull/2615

**Comment by okxiaoliang4** [comment]
LGTM.

**Pull request closed without merging**
