### PR TITLE
chore: disable pnpm side-effects-cache

### PR DESCRIPTION
**Pull request by sun0day**
### Description

Just a tip for setup `pre-commit` using `simple-git-hooks`

### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [x] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
Isn't `simple-git-hooks` already do it automatically?

**Comment by sun0day** [comment]
> Isn't `simple-git-hooks` already do it automatically?

It did not work in my local repo  😢. It's weird. You can close this PR for now. I'll find out why later.

**Comment by sxzz** [comment]
Yeah, we can just disable this option.

**Comment by sun0day** [comment]
> Yeah, we can just disable this option.

Done. Can you help review another 2 PRs @antfu @sxzz 

https://github.com/vueuse/vueuse/pull/2210
https://github.com/vueuse/vueuse/pull/2267

**Pull request merged**
