### PR TITLE
feat(useScrollLock): adds new option `avoidShake`

### PR DESCRIPTION
**Pull request by 0x-jerry**
### Description

When I use `useScrollLock`, there is a slight shake when switching between lock-on/lock-off.

Then, I think, maybe we can provide an option for users to avoid this shake.

And, here is an example of how it works:

https://user-images.githubusercontent.com/14226737/169635252-c06218cf-0a76-4da1-91c0-1f1b1210ac70.mp4

### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [x] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by wheatjs** [comment]
I don't know if we should be modifying the padding of the container element. This might produce undesirable results for the user? Does this take into account existing padding on the element?

**Comment by 0x-jerry** [comment]
@wheatjs Yes, this may produce an undesirable result, that's why this option is not enabled by default. And thanks for pointing out we should take care of the existing padding. I have fixed it by using the `getComputedStyle` method to get the correct padding value.

**Comment by wheatjs** [comment]
LGTM, only thing I think is maybe there could be a better name for it although I can't think of one myself 😅

**Comment by 0x-jerry** [comment]
How about `fixScrollbarPlaceholder`? or `tryFixScrollbarPlaceholder`? or just `scrollbarPlaceholder`?

**Comment by antfu** [comment]
Thanks for working on it. This seems to be a good-to-have feature. However, the implementation feels a bit too hacky for me. I think this fall into CSS's domain, which I'd consider out-of-scope of VueUse.

**Pull request closed without merging**
