### PR TITLE
feat(useStorage): add `waitOnMounted` option for SSR

### LINKED ISSUE #3447: Solve Hydration node mismatch for useStorage
### Clear and concise description of the problem

When using useStorage for app state like this:
```
export const useOrder = () => useLocalStorage<Order>('order', { items: [] })
```
The SSR will render UI with default value and client will render UI with saved state which will render to _Hydration node mismatch_ warning.

### Suggested solution

It would be nice if I can solve it like this:
```
export const useOrder = () => useLocalStorage<Order>('order', { items: [] }, { ssrUseDefault: true })
```

Which will set default value first and wait for page:finish hook.

### Alternative

Workaround:
```
export function useOrder () {
  const order = ref(defaultOrder)
  useNuxtApp().hook('page:finish', () => {
    const storedOrder = useLocalStorage<Order>('order', defaultOrder)
    order.value = storedOrder.value
  })
  return order
}
```

### Additional context

Maybe print warning when ssrUseDefault option was used in non-Nuxt environment.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by posva**
Close #3447

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Additional context

---

### <samp>🤖 Generated by Copilot at a84b5c3</samp>

Added a `waitOnMounted` option to `useStorage` to improve SSR compatibility. Updated the test file to cover the new option.

### <samp>🤖 Generated by Copilot at a84b5c3</samp>

*  Add `waitOnMounted` option to `useStorage` function to delay reading the storage value until the component is mounted ([link](https://github.com/vueuse/vueuse/pull/3504/files?diff=unified&w=0#diff-015d17be17c2a02d87f6b40bc47f526a5e82a01ee334f2883d271c6d98543d21R115-R121), [link](https://github.com/vueuse/vueuse/pull/3504/files?diff=unified&w=0#diff-015d17be17c2a02d87f6b40bc47f526a5e82a01ee334f2883d271c6d98543d21R153), [link](https://github.com/vueuse/vueuse/pull/3504/files?diff=unified&w=0#diff-015d17be17c2a02d87f6b40bc47f526a5e82a01ee334f2883d271c6d98543d21L173-R192))
*  Import `tryOnMounted` helper from `@vueuse/shared` to implement the deferred update logic in `useStorage` ([link](https://github.com/vueuse/vueuse/pull/3504/files?diff=unified&w=0#diff-015d17be17c2a02d87f6b40bc47f526a5e82a01ee334f2883d271c6d98543d21L3-R3))
*  Add test case for `waitOnMounted` option in `useStorage/index.test.ts`, using `defineComponent`, `nextTick`, and `mount` from `vue-test-utils` ([link](https://github.com/vueuse/vueuse/pull/3504/files?diff=unified&w=0#diff-0b0a7fdfc83097b808c0db980c965140cf7fa4874b0362ebc2f18f8aaf551b49L2-R4), [link](https://github.com/vueuse/vueuse/pull/3504/files?diff=unified&w=0#diff-0b0a7fdfc83097b808c0db980c965140cf7fa4874b0362ebc2f18f8aaf551b49R470-R488))

### CODE REVIEW

**Review by antfu — DISMISSED** [review]

**Comment by posva** [comment]
BTW: I think it’s worth checking with an native English speaker if the option name sounds good

**Comment by antfu** [comment]
Maybe `readOnMounted` or `readOnMounted`? To me, it's a bit unclear what to "wait" on

**Comment by posva** [comment]
Sounds good to me!

**Comment by Kronhyx** [comment]
@posva @antfu 

is there any way to use `sessionStorage` with **SSR** combined with `initOunMounted` or something similar


``` ts
const sessionQuery = useStorage('myCustomKey', {}, sessionStorage, {
  initOnMounted: true,
});
```


im getting this error when page load

> sessionStorage is not defined

**Pull request merged**
