### PR TITLE
fix: support complex Object type for useStorge

### PR DESCRIPTION
**Pull request by azaleta**
### Description
fix for issue #1939 

### Additional context

---

### What is the purpose of this pull request? 

- [X] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ ] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by sibbng** [comment]
This way they won't be deserialised back to Set, Map etc. Methods like `.has()`, `.set()` won't be available after reload and it will throw error again.

**Comment by azaleta** [comment]
@[sibbng](https://github.com/sibbng)
yes, this use case has some limitation right now.

suppose we init store as 
```ts
      a: new Set<number>(),
      b: new Map<string,string>()
```
after write to the store, they will all be the same value `[]`
in this case we could not know the type when we reload.

Now I convert all of them to Set.

**Comment by sibbng** [comment]
@azaleta We could store metadata in another property like `__usestorage__metada__`. Or directly in properties itself, like:

`{ a: new Set([1]) }` will be `"{ a: '__usestorage:set__[1]' }"` and we will remove `__usestorage:set__` prefix before deserializing and use this information to make it Set.

Also, currently we are serializing only the first level of `object`. We should deeply serialize-deserialize properties. But I'm not sure this is worth the added complexity.

**Comment by antfu** [comment]
I would suggest not doing this, since there is no perfect and straightforward way to solve it. If we can't correctly parse it, which could make the app fail silently, I would prefer to keep the current approach so the user aware they need to provide the custom serializer/deserializer them self and responsible for the caveats.

**Comment by antfu** [comment]
- Nested
- Recursive
- Map/Set
- Custom classes
- Dynamic (different types between the initial and serialized)
- Functions or other non-serializable data
- ...

Data serializing/deserializing is a very complex topic and should be handled by a standalone lib with its caveat. That's why the options are provided for customization. Thanks but this is out-of-scope of VueUse.

**Pull request closed without merging**
