### PR TITLE
refactor(useFtch): rename isFetchOptions to notFetchOptions

### PR DESCRIPTION
**Pull request by Valar103769**
### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ ] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
Sorry, why?

**Comment by Valar103769** [comment]
> Sorry, why?

顾名思义

**Comment by sxzz** [comment]
不是很能 get 到

**Comment by Valar103769** [comment]
> 
```js
 if (isFetchOptions(args[0])) {
        options = {
          ...options,
          ...args[0],

```
前提: option是指useFecth的参数,fetchOptions是指原生fetch的参数吧? 

如果args[0] 是fetchOptions,那么就把fetchOptions 的参数给option ? 这不是有问题吗?

**Pull request closed without merging**
