### PR TITLE
feat(useCanvasContext): new function

### PR DESCRIPTION
**Pull request by michealroberts**
### Description

This PR adds functionality for utilising the Web Canvas API with the aid of a composable, e.g.,

```ts
// This is the canvas HTMLCanvasElement element as a ref:
const canvas = ref<null | HTMLCanvasElement>(null)

// Get the ctx:
const { ctx } = useCanvasContext(canvas, '2d')
```

The returned context will be appropriately typed for `RenderingContext` needed.

### What is the purpose of this pull request? 

- [ ] Bug fix
- [X] New Feature
- [X] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [X] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by okxiaoliang4** [comment]
Oh my commits is gone~

**Comment by okxiaoliang4** [comment]
We can continue with the original [PR](https://github.com/vueuse/vueuse/pull/1373) and merge my [PR](https://github.com/michael-observerly/vueuse/pull/2) request in your fork repo

**Comment by michael-observerly** [comment]
@okxiaoliang4 Ah, I was going for a cleaner history on this. I made some further amends too.

**Comment by michealroberts** [comment]
Is there any movement on this one @okxiaoliang4 ? :)

**Pull request closed without merging**
