### PR TITLE
fix(useStorage): set/parse object value with null default value

### LINKED ISSUE #576: [object Object] after storing object after null in useLocalStorage
```js
import { useLocalStorage } from '@vueuse/core'

const data = useLocalStorage('test', null)
data.value = {hello: 'world'}
```

[Demo](https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JlDxJgCtUAF9GHHweEAABBdJkRGHkfWsqETZObiJxoRExCSlZeREADKT0QVAaiHSd38gWCdBQky6HB6vD6AyGoy+Uxmc2u5Fu90elTBlwArJMAAyTACM62wWx2yD2hxAJzOBCIeMQBOGM2sr3YXAuWJ+KD+MjkCl4AGFWBFEFAAeZWCYUHdsLJ8oUVLK8GBWMg4fIMrDZCgkSiQGjBiMxgIhNNZsMuTy+YgyZSaXSGbsDscALrMIx0AzmtCgACCYDAkwW6FAqT1BggqSIr3F0iIdD1dWkKmA-juRVYUEMQISFSQKiONQ4sxUAHIXXdeXVEA2ADrYLszbDIPNUFOuAC8hcQxdLBnLdQQiG0DdS-YbjBU2FIEXsXcH0ggscMqlHwF0ni8aEbkTqBioDaOrKORyAA)

Screen Shot 2021-06-11 at 08 04 09

If I replace `null` with `{}` it will work as expected

### PR DESCRIPTION
**Pull request by mxmvshnvsk**
fixes #576

### CODE REVIEW

**Comment by antfu** [comment]
I don't feel the `try-catch` is a right way to do as it's kinda opaque to users, and will overrides syntax error and introduce potentially perf lose. I have exposed `StorageSerializers` in 2c8ac0c2c4cd28b93ed0a08f691448b8d9d49a2d (v4.1.3). The recommend way of doing this is explicitly set the serializer on the user side.

```ts
import { useStorage, StorageSerializers } from '@vueuse/core'

useStorage('key', null, { serializer: StorageSerializers.object })
```

**Comment by mxmvshnvsk** [comment]
@antfu Then it will be correct to explicitly reflect this in the documentation, I think this case appears for many.

**Comment by antfu** [comment]
1aad4975e09a75ea7c68dda8e090f4f9926780d4

**Comment by xorik** [comment]
Thanks @antfu, now it's clear why it wasn't working as expected

**Comment by MrEldin** [comment]
> I don't feel the `try-catch` is a right way to do as it's kinda opaque to users, and will overrides syntax error and introduce potentially perf lose. I have exposed `StorageSerializers` in [2c8ac0c](https://github.com/vueuse/vueuse/commit/2c8ac0c2c4cd28b93ed0a08f691448b8d9d49a2d) (v4.1.3). The recommend way of doing this is explicitly set the serializer on the user side.
> 
> ```ts
> import { useStorage, StorageSerializers } from '@vueuse/core'
> 
> useStorage('key', null, { serializer: StorageSerializers.object })
> ```

Thank you, you helped me a lot, I searched a lot for a solution.

**Pull request closed without merging**
