### PR TITLE
feat(watch): shorthands for watch

### PR DESCRIPTION
**Pull request by mrhammadasif**
### Description

We often have to watch for objects with `{deep: true}` or `{immediate: true}` ~~or both `{deep: true, immediate: true}`~~. I just added few shortHands **watchDeep** and **watchImmediate** ~~and **watchDeepImmediate**~~ to avoid writing them explicitly each time

Update 20 Feb, 2023: Removed `{watchDeepImmediate}` shorthand as suggested by @antfu 

### Additional context

These shorthands are based on `shared/watchOnce`

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
I think I am ok with having `watchDeep` and `watchImmediate`. But `watchDeepImmediate` feels a bit too much for me, as we can't really introduce all the combinations.

**Comment by mrhammadasif** [comment]
> I think I am ok with having `watchDeep` and `watchImmediate`. But `watchDeepImmediate` feels a bit too much for me, as we can't really introduce all the combinations.

Well, there are many cases while writing an application where you want to do both of them. Do you have any better idea to write a shortcut for the combination?

**Comment by antfu** [comment]
I would honestly think 

```ts
watchDeep(s, f, {
  immediate: true
})
```

would be enough. Or otherwise, I don't think we should provide something like `watchPostDeepImmediate`

**Comment by mrhammadasif** [comment]
> I would honestly think
> 
> ```ts
> watchDeep(s, f, {
>   immediate: true
> })
> ```
> 
> would be enough. Or otherwise, I don't think we should provide something like `watchPostDeepImmediate`

I have updated the PR, and removed the `watchDeepImmediate` as you suggested

**Comment by mrhammadasif** [comment]
Any update on this ?

**Review by antfu — APPROVED** [review]

**Pull request merged**
