### PR TITLE
fix(useThrottleFn): `trailing` option should be `false` by default

### LINKED ISSUE #1684: useThrottleFn 快速点击会触发两次
### Describe the bug

如果在设定时间内，快速点击多次，useThrottleFn 内的方法会触发两次，第一次在点击的时候触发，第二次触发是在 useThrottleFn 定时结束后触发。不知是原先就如此设计，还是因为 bug。如果设计如此是否有违 throttle 方法在短时间内只触发一次的原则。希望官方可以给个解答。

### Reproduction

https://github.com/vueuse/vueuse/blob/main/packages/shared/useThrottleFn/demo.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 7.20 GB / 15.92 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.33)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^5.3.0 => 5.3.0
    vue: ^3.2.33 => 3.2.33
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by webfansplz**
### Description

Close #1684 

Follow the design principles of `throttle function`,I think we shouldn't  call fn again by default after the time is up .

### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by septatrix** [comment]
I just saw this in the BREAKING CHANGES section of the release notes.

The correct behaviour should be to only call the function after expiration of the timeout if any throttled call occured since the last call which was forwarded to the wrapped function. This is also how underscore implements it IIRC.
In most cases (e.g. resize, scroll, input) you want to run the function one last time if a change occurred between the last time the wrapped function was called.

I am not sure what you refer to by "design principles of throttle function". The event will still only be called at most once per interval. And those which would like the other behaviour can use `trailing: false` though the cases where this is the correct behaviour are rare in comparison to the indented use cases like the ones given in the docs.

It remember there was a way to search all of github how some APIs were used which could be used to confirm that most people use the previous default though I am not sure how to do this (the normal github search is not really suited for this)

**Comment by septatrix** [comment]
@antfu I see that v9 is released now. Could this be reconsidered for v10?

**Comment by septatrix** [comment]
Or at least add a TIP/WARNING box like it is done for some other function about this behaviour

**Comment by septatrix** [comment]
Also all other throttle related helpers `watchThrottled`, `refThrottled`, `throttleFilter` default to `trailing = true` affirming my statement about it being the expected and more reasonable default in most cases.

**Comment by antfu** [comment]
Yeah I think it's reasonable to have it default to `true`, refer to loash https://lodash.com/docs#throttle

@septatrix You can send a PR to change it back and we will ship if in v10

**Comment by septatrix** [comment]
> @septatrix You can send a PR to change it back and so we could ship it in v10

Sure thing!

**Comment by septatrix** [comment]
Sorry I currently cannot say when I will have time to work on this

**Pull request merged**
