### PR TITLE
feat(fsApi/useFileSystemAccess): Finish / complete File_System_Access_API wrapper - potentially needs to be an add-on

### LINKED ISSUE #1466: Add directories to the useFileSystemAccess function
### Clear and concise description of the problem

According to the docs of the [File_System_Access_API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API), the browsers that support it also support [directories](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle).

Managing directories or having access to a whole directory can be huge for web apps that need to manage lots of data or perform administrative tasks on the filesystem.

### Suggested solution

There's enough shared functionality between creating and managing, files and directories, that for the most part the existing `useFileSystemAccess` api could be extended to support directories. 

Because the possible recursive nature of directories, it could get pretty complicated, and that may require parts of it to be broken out separately.

### Alternative

It could probably be implemented in userspace, but because the datatypes are set within `useFileSystemAccess` it would be hard to use both `useFileSystemAccess` and the direct native api at the same time.

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by josh-hemphill**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

The current filesystem API wrapper ( [useFileSystemAccess](https://vueuse.org/core/useFileSystemAccess/) ) only covers a very limited bit of the [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API).
Chromium-based browsers can open and navigate from file to folders and back, starting from one of three "pickers", almost none of which is covered by the current implementation.

The full [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) is a pretty large and complex web API, but still one I believe benefits greatly from being wrapped by Vue reactivity and utilities. So I've broken it out as an add-on module since it really requires multiple functions and a couple classes or class-like data structures to manage and interact with files and folders.

The added functionality mostly just wraps the browser's API with a few utilities added.

The data types the browser uses, file and directory handles, are wrapped as classes with controllable/optional caching when the data is read from disk.

### Current Status:

- [x] Basic functionality
- [x] Demos
- [x] Documentation
- [ ] ~Tests~ (Couldn't find a way to stub low level functionality like the FS API)

closes #1466
---

### <samp>🤖 Generated by Copilot at 1363be9</samp>

This pull request adds a new package `@vueuse/fsApi` that provides utilities for the file system access API. It includes classes for wrapping file and directory handles, functions for using file pickers, and documentation and demo components for the package.

### <samp>🤖 Generated by Copilot at 1363be9</samp>

*  Add a new package `@vueuse/fsApi` that provides utilities for the file system access API ([link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-d3ba748b6652bb9dd1e2321d187d6e58a02342a8ac28cfdd3082e5661117d1a8R1-R7), [link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-b3ede5f6fae0451f13d473ae8768e4e86f6385c176c551034e3c855d86f65c88R1-R43), [link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-890768bd0f95bf4dbb013dbc3fe5f91ade3e2b1102afb3de72cb86e51420f07bR1-R21))
*  Define the types and interfaces for the file system access API and the `@vueuse/fsApi` package ([link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-de59f22c127f03692facda7cab86b577b94c86c4f7f92f4552050dfde002263dR1-R153))
*  Export an abstract class `FsHandle` that is inherited by `FsFile` and `FsDirectory` and provides common properties and methods for file system handles ([link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-fd9a69ccc1c737fed2dfe4f5e195b835884d3dc281cfa6edf1f12ffe1bbfd195R1-R27))
*  Export a class `FsFile` that wraps the native `FileSystemFileHandle` and provides reactive and convenient methods for working with files ([link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-2e6dfe1e01ee21ccf15fda88209259972231597561111c2becb8219f43fe285cR1-R96))
*  Export a class `FsDirectory` that wraps the native `FileSystemDirectoryHandle` and provides reactive and convenient methods for working with directories ([link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-27646bd68b329b51d52cec9f7bafd20f154d63878a5f4016d91a86db20006d12R1-R195))
*  Export a function `useOpenFilePicker` that provides a reactive and convenient way to use the `showOpenFilePicker` function from the file system access API ([link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-e9fcf0a474166ac6b8696ae6711066593f0ffa76e5c1c83db17b28bde59921d8R1-R37))
*  Export a function `useSaveFilePicker` that provides a reactive and convenient way to use the `showSaveFilePicker` function from the file system access API ([link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-1510c57be781f7f88c9c6f3c4f5916ab286462d8b3c788b253d2ad837758f779R1-R87))
*  Export a function `useDirectoryPicker` that provides a reactive and convenient way to use the `showDirectoryPicker` function from the file system access API ([link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-2ea266a1a51917818ec3b4631fd680654e4349c0316c65b51782b015ded2d6d8R1-R47))
*  Provide a documentation for the `useSaveFilePicker` function from the `@vueuse/fsApi` package ([link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-db5ba72d41753dfb710d972cfdb89f2a22572d2b89e1e89780a234b522c53558R1-R22))
*  Provide a demo component for the `useSaveFilePicker` function from the `@vueuse/fsApi` package ([link](https://github.com/vueuse/vueuse/pull/3122/files?diff=unified&w=0#diff-bae7d7f711103f59132747347560093b0e627a68686aefd3fdbe5461224e8774R1-R79))

### CODE REVIEW

**Comment by josh-hemphill** [comment]
Just waiting on any kind of feedback

**Comment by josh-hemphill** [comment]
I still think this is rather important, it's currently an incomplete implantation.

**Comment by josh-hemphill** [comment]
Finally got all the demos working, and enough docs to get started.

**Comment by antfu** [comment]
Thanks for your PR! However, as noted, we are not taking new functions at this moment. Giving the complexity this involves, I suggest you to publish it as your own package to move forward and iterate, without us blocking you (in context that FS API is still quite new, there might requires some flexibility to experiment the best practice). Unfortunately VueUse can't take that complexity right now. Thank you and sorry for the late response.

**Pull request closed without merging**
