### PR TITLE
fix(useWebSocket): urlRef changes were not being tracked

### PR DESCRIPTION
**Pull request by ferferga**
### Before submitting the PR, please make sure you do the following

- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

URLRef changes were not being tracked inside useWebSocket

### CODE REVIEW

**Comment by GarlandQian** [comment]
If I haven't opened the WebSocket, I think it shouldn't be opened directly when the URL changes. It should maintain the current state.

**Comment by GarlandQian** [comment]
If I haven't opened the WebSocket, I believe it shouldn't be opened directly when the URL changes. It should maintain the current state. Even when the immediate parameter is set to false, I think regardless of the current WebSocket state, it should be closed directly.

**Comment by ferferga** [comment]
@GarlandQian In that case, what's the benefit of using useWebSocket instead of the "raw" WebSocket instance?

This is a regression, not a new feature.

**Comment by DrColossos** [comment]
Sorry to jump in here: this just arose as a "bug" in our internal app. I was surprised with the behavior, especially since I use `immediate: false`. This is somehow unexpected since we have another server that retrieves the current websocket URL and passes it on to `useWebsocket` to be triggered at a later point in time.

**Comment by ferferga** [comment]
@DrColossos First of all, this PR fixed a regression, so that behaviour worked in your application by "taking advantage" of that regression. But according to what's stated in the docs, what you say is the behaviour that it should have.

In either case, in my opinion the docs are incorrect and the implementation is right: in all other composables, `immediate` just controls if the composable starts at the beginning or not, instead of whether "reacting to effects" is enabled or not. Having the option to disable the "reactivity" makes no sense in this library, since the sole reason to exist is to make common APIs easy to use reactively.

In your case, I think your logic can easily be simplified: why not have that URL be computed (or `computedAsync` from this library if it's fetched from a server with reactive params) and pass that to this composable? If that computedref is turned nullish, the socket will disconnect, if the URL changes, the socket will point to the new one accordingly, in the same way you expect a component's DOM to update when it's reactive dependencies are updated.

**Comment by DrColossos** [comment]
Thank you for you info. I was reading the `immediate` flag "Automatically open a connection" from the source of the types. Looking at the rest of the online docs, I see full the description of the flag states what you say. I was only looking at the types. 

Anyways, thanks for clarification!

**Pull request merged**
