### PR TITLE
feat(useEyeDropper): add throw on Error

### PR DESCRIPTION
**Pull request by jenjen75**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

When eyedropper is opened but canceled (eg : Escape), the promise function `open` is rejected, resulting a global error `DOMException: Failed to execute 'open' on 'EyeDropper': The user canceled the selection.` when attached directly to template event listener like `@click="open"`.

This PR resolve this issue by wrapping the promise into try/catch

### Additional context

---

### <samp>🤖 Generated by Copilot at 0e7088d</samp>

Fixed error handling for `useEyeDropper` hook by adding try-catch block to `open` function. This resolved issue #1022 and followed the browser API spec.

### <samp>🤖 Generated by Copilot at 0e7088d</samp>

*  Handle possible errors from `eyeDropper.open` method with a try-catch block ([link](https://github.com/vueuse/vueuse/pull/3113/files?diff=unified&w=0#diff-ba8585e1b77940a97094e847b8ea8e16f0fd12d6a07391c5965940c910dd2b7cL42-R46)). This fixes issue #1022 and follows the browser API specification.

### CODE REVIEW

**Comment by okxiaoliang4** [comment]
I think we should throw the error.
Because maybe has other kind error.

**Comment by okxiaoliang4** [comment]
Maybe we can add a new option like `throwOnError`?

**Comment by jenjen75** [comment]
Thank you for your reply :)
This is a good idea to preserve both behaviour.

**Review by okxiaoliang4 — APPROVED** [review]

**Comment by antfu** [comment]
Emm, I am not sure if I understand - it throws the error already, right? Why catch it and rethrow?

**Comment by okxiaoliang4** [comment]
Because the new option allows us to continue to deal with error.

```ts
const { open } = useEyeDropper({
  throwError: true
})
const result = await open().catch(error => {
  // do some thing.
  throw error
})
```

**Pull request closed without merging**
