### PR TITLE
feat(firebase): add support for firebase@9

### PR DESCRIPTION
**Pull request by peterekjs**
#697

Adds support for Firebase 9 SDK

### CODE REVIEW

**Comment by antfu** [comment]
Thanks a lot for this! I'd expect that projects need time to take the migration and it would be better for us to support both versions for a while instead of cut the line and make breaking changes. Would you mind creating a new package like `@vueuse/firebase-9` instead so we release them together.

Or ideally, we could have sub modules `@vueuse/firebase/9` and `@vueuse/firebase/8` which the default export `@vueuse/firebase` could be an alias for either version (guess we stay `8` for now, and switch to `9` in the next major bumping for VueUse). This way might need some tweaks to the build scripts and might have some type conflicting, feel free to give it a try. Or if it's too complex, I am also fine with a separate package approach.

Thanks!

**Comment by peterekjs** [comment]
Absolutely agree. The solution with 2 submodules (`@vueuse/firebase/9` and `@vueuse/firebase/8`) and using version `8` as default export for `@vueuse/firebase` before next major version seems to me as the best option here. I'll try playing with it a bit.

**Comment by ub3rb3457** [comment]
when can we expect this functionality to be implemented?

**Comment by peterekjs** [comment]
At the end I came up combining both approaches. To make sure, that `@vueuse/firebase` is compatible with `Firebase 8` (and it's imports) and to ensure, that library supporting `Firebase 9` will be installable via `npm` or `yarn`,  it is necessary to create a separate package, hence I added `@vueuse/firebase-9`. 

In order to mimic current `Firebase 9` module structure described by [upgrade guide](https://firebase.google.com/docs/web/modular-upgrade) I played a bit with bundling scripts to allow package nesting, so we have `modular` library accessible directly as `@vueuse/firebase-9` and `compat` library accessible as `@vueuse/firebase-9/compat`.

Could you, @antfu, please take a look into the commits?

**Pull request closed without merging**
