### PR TITLE
feat(useForm): Form state management and rule validation

### PR DESCRIPTION
**Pull request by LittleSound**
### Description

This draft was made for issue #1590, which is meant to make a utility function `useForm` to simplify form manipulation.

### TODO:

- [x] Improve the functionalities
  - [x] Use reactive type to return the form
  - [x] For a single rule, the array can be omitted
  - [x] Mark whether the value of the form has been modified
- [x] Unit tests
- [x] Documentations
- [x] Better type definations for Typescript

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
This is a quite complex topic to solve and ppl might have different preferences in using it. Instead of having the logic inside of `@vueuse/core`, I think having it as a separate package would better help it to integrate. I'd suggest you create one of your own to experiment with it. Later on, if it turns out great, I am happy to provide feedback on it and maybe move it to something like `@vueuse/form` like our other packages. Thanks for your contribution.

**Comment by LittleSound** [comment]
> This is a quite complex topic to solve and ppl might have different preferences in using it. Instead of having the logic inside of `@vueuse/core`, I think having it as a separate package would better help it to iterate and experiment on different API designs. I'd suggest you create one of your own to experiment with it. Later on, if it turns out great, I am happy to provide feedback on it and maybe move it to something like `@vueuse/form` like our other packages. Thanks for your contribution.

Can you give some advice on how to conduct this experiment. I can use it in my own project, but I don't know if it's enough for an experiment?

**Comment by okxiaoliang4** [comment]
Maybe you need this? https://github.com/vueuse/vueuse/pull/1497

**Comment by antfu** [comment]
I think at the first step you could publish the package as-is and collect feedback on how the APIs work in the real world.

**Comment by LittleSound** [comment]
> Maybe you need this? #1497

I didn't find this `useAsyncValidator` in my previous search, It may have something to do with the search terms I use
It seems to be doing the same thing as my `useForm`, does this mean that my `useForm` is not needed, I am confused

Maybe my submission of issue #1590 didn't get much attention and made me misjudge whether vueuse needed this feature?

**Comment by okxiaoliang4** [comment]
in #1497 is dependent on `async-validator`. If you think `async-validator` does not meet your needs or don't want other dependent you can refer to antfu's comments.

**Comment by LittleSound** [comment]
I think I'll finish `useForm` because I like  the way I designed the implementation myself and want it to be used in projects.

**Comment by SnowingFox** [comment]
> I think I'll finish `useForm` because I like the way I designed the implementation myself and want it to be used in projects.

Maybe you can join the [vue-use-form](https://github.com/vue-use-form/vue-use-form), i had decide to rewrite the main logic. if you have interest, i can invite u

**Comment by LittleSound** [comment]
> I think at the first step you could publish the package as-is and collect feedback on how the APIs work in the real world.
> 
> 
> 
> It would also be great if you can do a simple comparison with existing solutions in the package's README and show why this version stands out / or what's strengths of it.

I used this weekend to build the slimeform repository, and I will continue to refine it later

https://github.com/LittleSound/slimeform

**Comment by SnowingFox** [comment]
> > I think at the first step you could publish the package as-is and collect feedback on how the APIs work in the real world.
> > It would also be great if you can do a simple comparison with existing solutions in the package's README and show why this version stands out / or what's strengths of it.
> 
> I used this weekend to build the slimeform repository, and I will continue to refine it later
> 
> https://github.com/LittleSound/slimeform

I'm looking forward to your form lib

**Pull request closed without merging**
