### PR TITLE
feat(integrations): add useTitleCase

### PR DESCRIPTION
**Pull request by hengshanMWC**
### Description

wrapper for  [`title-case`](github.com/blakeembrey/change-case) to useTitleCase

> Transform a string into title case following English rules.

### Additional context

catalogue: packages/integrations/useTitleCase

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [X] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [X] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
How about a more general util like `useStringCase` with an addtional argument for the case style?

**Comment by hengshanMWC** [comment]
> How about a more general util like useStringCase with an addtional argument for the case style?

wrapper for [stringcase]('https://www.npmjs.com/package/stringcase')？Or make it `packages/core/useStringCase `. It seems that both of them need to be done again. We can only close this module

**Comment by antfu** [comment]
I mean, since you are warpping `change-case`, that have a lot more cases. We could have the wrapper configurable like:

```ts
useStringCase(strRef, 'camelCase')
useStringCase(strRef, 'pascalCase')
// ...
```

**Comment by wheatjs** [comment]
Maybe something like this. I think it is a good idea to have the package name in the function name for integrations.

```ts
const titleCase = useChangeCase(value, 'titleCase')
```

**Comment by antfu** [comment]
Yeah, I agree with calling it `useChangeCase`

**Comment by hengshanMWC** [comment]
ok, I'll try

**Comment by hengshanMWC** [comment]
[New PR](https://github.com/vueuse/vueuse/pull/1371)
Then I'll close this PR

**Pull request closed without merging**
