### PR TITLE
docs(guidlines): added guidelines

### PR DESCRIPTION
**Pull request by wheatjs**
Here is an initial draft for the guidelines. Let me know if you guys have any suggestions or corrections.

@antfu @cawa-93

### CODE REVIEW

**Comment by cawa-93** [comment]
1. I would like see some examples (code or links to code) in general section, Because some points may not be clear. What I mean:
    > Use configurableWindow (etc.) when using global variables like window
  
    It's not clear what is `configurableWindow`. Link to some function with usage will be very helpful. 
    
2. How about add a bit points about "Where from import any functions"? What I mean: Today I just experimented. I Wrote `compute` and my IDE proposed me auto import from `vue`, `@vue/reactive-api` and `vue-demi`. And it happens often. And every time I worry about doing everything right. I would be calmer if the rules set what and where I can import.

**Comment by cawa-93** [comment]
And, just interesting
@antfu 

> Use 'ref' over 'reactive' whenever possible

Why? 😅

**Comment by antfu** [comment]
> Use 'ref' over 'reactive' whenever possible

https://www.youtube.com/watch?v=IMJjP6edHd0

**Comment by wheatjs** [comment]
@cawa-93 good suggestions, I'll add some examples tonight

**Comment by antfu** [comment]
Let's have it first, we could update them later.

**Pull request merged**
