### PR TITLE
feat(useTouchMove):add a new hook for monitor touch event

### PR DESCRIPTION
**Pull request by Zourunfa**
### Description

Its main function is to monitor the sliding distance and direction of the contact on the screen.
This hook is only applicable to the mobile terminal. The internal code uses touchevents.

### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [yes ] New Feature
- [x] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by Zourunfa** [comment]
This is the first time I mentioned PR, so it ended and was rejected

**Comment by Zourunfa** [comment]
This is the first time I mentioned PR, so it ended and was rejected 哈哈

**Comment by wheatjs** [comment]
Does this differ from https://vueuse.org/core/useswipe/?

**Comment by Zourunfa** [comment]
> Does this differ from https://vueuse.org/core/useswipe/?
Sorry, I was careless, thank you for your comment, it is a kind of encouragement for me, I think I will find other features again to mention

**Comment by wheatjs** [comment]
No worries at all, thanks for the PR! We appreciate all contributions!

**Pull request closed without merging**
