### PR TITLE
feat(useMouseDistanceToElement): new function

### PR DESCRIPTION
**Pull request by michealroberts**
This composable returns the scalar distance in pixels to the nearest edge point of an element relative to some mouse position { x, y }.

This useful when there is a need to detect use intentions - and could be utilised for lazy loading routes or resources by predictively detecting where a user is "going" prior to hovering (e.g., something like as a user moves close to a collapsed sidebar, as the user moves towards it it reveals).

This could also be used in the context of animations ... detecting intentions of a user, animating CTAs as a user moves "close" to the element etc.

### CODE REVIEW

**Comment by michael-observerly** [comment]
@webfansplz Sorry to notify directly, but I see you are quite active at the moment in this repo ... it would be nice to get some feedback about this ... I feel like this would be really useful for detecting the pixel distance between the current mouse position to any element * **boundary** * on the page.

**Comment by michael-observerly** [comment]
cc. @okxiaoliang4

**Comment by okxiaoliang4** [comment]
Thank your contribute. But i can't review your pr,I'm out few days

**Comment by michael-observerly** [comment]
> Thank your contribute. But i can't review your pr,I'm out few days sorry.

No worries, thank you for the prompt response. :)

**Comment by webfansplz** [comment]
Thanks for the PR.

I'm not so sure about it, it seems just provide two computed state based on `useMouseInElement`.

If ppl has similar needed, perhaps the combination of states provided based on `useMouseInElement` would be more flexible ?

**Comment by michael-observerly** [comment]
@webfansplz Totally understand, the original PR was #1086 which did exactly that. 

But with discussions with Anthony, it was decided for performance reasons* that we should maybe place this in an extended function to be used if needed ... or in a private library. However, I feel that this would be useful to add ... perhaps maybe it should just return the calculation needed for getting the distance to the boundary.

*(for me, on my Mac M1 I see minimal performance degradation, but maybe for other devices ... it's obviously heavy).

**Comment by michael-observerly** [comment]
@webfansplz Also, I totally understand the combination aspect, but the maths is not entirely trivial or easy to calculate ... I have two degrees (Physics and Astrophysics) and it wasn't trivial to sketch out the problem ... and reduce to what I have added. (It involves understand the space around the box, relative to the box, and disseminating various sections around the box). 😝

**Comment by okxiaoliang4** [comment]
Maybe we can add`useDistance(pointA: MaybeRef<Point>, pointB: MaybeRef<Point>)`in this pr

**Comment by michael-observerly** [comment]
@okxiaoliang4 @webfansplz Yeh that could work, but the caveat is that it is hard to detect say Point A, the closest point to an element's boundary ... imagine a line from the center of the element, to PointB. PointA is on that line, but it's not a trivial calculation to know where PointA is :)

**Comment by michael-observerly** [comment]
I'll provide a quick diagram ... * one moment

**Comment by okxiaoliang4** [comment]
I mean maybe can add a other function `useDistance` in this pr :)

**Comment by michael-observerly** [comment]
@okxiaoliang4 Ahhh ok, yeh I agree with that. I will refactor a few bits for that and get it pushed. I'll maybe wait for @antfu 's final decision on this before.

**Comment by okxiaoliang4** [comment]
We may release a new package `@vueuse/math`. https://github.com/vueuse/vueuse/pull/1224#issuecomment-1034560523

**Comment by michael-observerly** [comment]
Frame 2

**Comment by michael-observerly** [comment]
> We may release a new package `@vueuse/math`. [#1224 (comment)](https://github.com/vueuse/vueuse/pull/1224#issuecomment-1034560523)

Yeh, maybe release the calculation in this package, and utilise it within this PR?

**Comment by okxiaoliang4** [comment]
Wait for antf opinion :)

**Comment by michael-observerly** [comment]
Yeh :) for sure, thank you for all of the discussions. I know I'm fighting hard for it but I think it's a rather elegant solution :)

**Comment by michael-observerly** [comment]
@antfu Any thoughts on this?

**Comment by michealroberts** [comment]
@antfu @okxiaoliang4 Closing this now. Disappointing.

**Pull request closed without merging**
