### PR TITLE
feat(OnClickOutSide) use slot scope to avoid add excessive element

### PR DESCRIPTION
**Pull request by smallnine9**
### Before submitting the PR, please make sure you do the following

- [√ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ √] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [√ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [√ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ √] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

This PR is to solve the issue #2947 
When we use OnClickOutSide to wrap an element, the OnClickOutSide will auto generate a 'div' element( or we specify an custom tag using prop.as)
Maybe we would think this is an insignificant  point, but in some case, I found it will cause bad dx, first, we can wirte `demo.vue` like that:
```
<script lang="ts">
import * as v from 'vue'
import { OnClickOutside } from './component'

export default v.defineComponent({
  components: { OnClickOutside },
  setup() {
    const color = v.ref('green')
    return { color }
  },
})
</script>

<template>
  <OnClickOutside @trigger="color = 'red'">
    <section class="base" :class="`bg-${color}`" @click="color = 'green'">
      &nbsp;click
    </section>
  </OnClickOutside>
</template>

<style>
.base {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100px;
  height: 100px;
}

.bg-green {
  background-color: green;
}
.bg-green::before {
  content: "inside";
}

.bg-red {
  background-color: red;
}
.bg-red::before {
  content: "outside";
}
</style>
```
and then we run `nr dev`, we open the website and choose onClickOutSide, we can find the problem:
image

For users ，we just want to make the `section` element be  **onClickOutSideable**, but because the extra div element is larger than the section elment, even we click outside of section, it could not change color of section element.

so, this is an an annoying problem。

### Additional context

I just passed the target ref to user, and user can bind this target to the element **_directly which they really want to make onClickOutSideable_**

But it will change the way how users using onClickOutSide, and maybe there exists a better solution。
This is my first PR to vueuse, so I am very glad to obtain feedback from maintainers.

Can I ask how you test your changes?
For me, this PR, I just modify the demo.vue in onClickOutSide folder, but I feel it's a little inconvenient.
when I open playground, I found it can't just import OnClickOutSide from @vueuse/components, maybe we can add the config in vite.config.js?
image

---

### <samp>🤖 Generated by Copilot at 66f5243</samp>

Refactored the `onClickOutside` component to remove unnecessary props and simplify its slot usage. The component now allows customizing the click outside element through the `target` ref.

### <samp>🤖 Generated by Copilot at 66f5243</samp>

*  Simplify component rendering to use default slot as a render function ([link](https://github.com/vueuse/vueuse/pull/2966/files?diff=unified&w=0#diff-3c599ae86e0d1c36cb38cc7f76591f0e19ff5aa4132a25b338920aca4c0ff484L12-R12), [link](https://github.com/vueuse/vueuse/pull/2966/files?diff=unified&w=0#diff-3c599ae86e0d1c36cb38cc7f76591f0e19ff5aa4132a25b338920aca4c0ff484L22-R22))

### CODE REVIEW

**Comment by sibbng** [comment]
Couldn't we keep `as` option and also support default slot? 🤨

**Comment by smallnine9** [comment]
so, can we continue discussion or just deal with it?

**Comment by smallnine9** [comment]
@wheatjs what's your opinion? :)

**Comment by antfu** [comment]
This will be a breaking change, and would not work them the slot has multiple components. We should do it in a non-destructive and braking way. 

Maybe support `:as="null"` to bypass creating an element.

**Comment by smallnine9** [comment]
Yes, I didn't consider it thoroughly before. We should make it compatible with the previous users' habits. I added `:as="null"` to indicate that the user wants to use OnClickOutside without adding extra elements. 
For cases where there are multiple components in the slot, users can bind the target to multiple components.
like that:
```
  <OnClickOutside v-slot="{ target }" :as="null" @trigger="color = 'red'">
    <Foo :ref="target" :color="color" @change-color="color = 'green'" />
    <Foo :ref="target" :color="color" @change-color="color = 'green'" />
  </OnClickOutside>
```
 However, is there any issue with this?

**Comment by smallnine9** [comment]
delete branch carelessly， Could this open again？

**Pull request closed without merging**
