### PR TITLE
fix(useFetch): mark `isFinished`, `isFetching` readonly

### LINKED ISSUE #3617: [useFetch] isFinished,isFetching to ComputedRef
### Describe the bug

isFinished isFetching can never be changed externally, set them to ComputedRef to avoid possible 
ambiguity.

### Reproduction

none

### System Info

```Shell
none
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by baboon-king**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

fix #3617 

### Additional context

`isFinished` `isFetching` can never be changed externally, set them to `ComputedRef` to avoid possible ambiguity.

### CODE REVIEW

**Comment by baboon-king** [comment]
close #3617

**Comment by baboon-king** [comment]
> It's probably better to use [readonly](https://vuejs.org/api/reactivity-core.html#readonly) instead

MVP

**Review by antfu — APPROVED** [review]

**Review by antfu — APPROVED** [review]

**Review by baboon-king — COMMENTED** [review]
right!

**Comment by aparajita** [comment]
Actually these properties could be changed externally, and in my case I did, because I have persistent UseFetchReturn objects whose state needs to be reset at various points without actually executing a fetch.

This is the second time I have been bitten by breaking changes like this that required a significant amount of recoding. I'll have to start watching the repo so I can comment on such breaking changes before they are made.

**Comment by service-paradis** [comment]
> Actually these properties could be changed externally, and in my case I did, because I have persistent UseFetchReturn objects whose state needs to be reset at various points without actually executing a fetch.
> 
> This is the second time I have been bitten by breaking changes like this that required a significant amount of recoding. I'll have to start watching the repo so I can comment on such breaking changes before they are made.

Oh god! Same here and there is no easy workaround right now!

**Comment by aparajita** [comment]
@service-paradis I was able to work around it by creating `isFinished` and `isFetching` refs of my own and adding a watch on the `UseFetchReturn` refs to update my refs. I can then set the value of my refs.

**Pull request merged**
