### PR TITLE
fix(useAxios)!: `error` should return type `unknown`

### PR DESCRIPTION
**Pull request by jbaubree**
> **Warning**: **⚠️ Slowing down new functions**
>
> Due to the growing audience of VueUse, we received a huge amount of feature requests and pull requests. It's become harder and harder and recently a bit beyond our capacity to maintain the project. In the near future, **we could like slowing down on accepting new features and prioritize the stability and quality of existing functions. New functions to VueUse may not be accpected**. If you come up some new ideas, we advice you to have them in your codebase first instead of proposing to VueUse. You may iterate them a few time and see how them suite your needs and how them can be generalized. If you **really** believe they are useful to the community, you can create PR with your usercases, we are still happy to hear and discuss. Thank you for your understanding.

### Description

fix(useAxios): add typing for onError param

### What is the purpose of this pull request? 

- [X] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by Alfred-Skyblue** [comment]
In the response interceptor, what we throw out is not necessarily AxiosError type.

**Comment by jbaubree** [comment]
@Alfred-Skyblue i don't understand why error is typed with AxiosError ?
Capture d’écran 2023-02-23 à 09 01 04

**Comment by antfu** [comment]
Yeah, I think instead, the return `error` ref should be typed as `unknown`

**Comment by Alfred-Skyblue** [comment]
> Yeah, I think instead, the return `error` ref should be typed as `unknown`

I thought it was a breaking change, but it's right

**Review by antfu — APPROVED** [review]

**Pull request merged**
