### PR TITLE
feat(reactivePick): allow ref picks

### LINKED ISSUE #460: [feature] reactivePick: support computed keys
Currently `reactivePick` allows you to pick options from an object and have the resulting object be reactive. While this is already useful, the function could be made a lot more useful if it was possible to also have the picking action itself be reactive, i.e. the keys to pick supporting a `Ref`. In my use case I have a component wrapping three subcomponents, and I want to pick the subcomponents props from the wrapper components props since not all subcomponents use all props (I have to keep this design for backwards compatibility).

I propose the following change (and I'll try to create a PR later):

Add a new overload to `reactivePick`:
```typescript
reactivePick<T extends object, K extends keyof T>(obj: T, keys: MaybeRef<K[]>): Ref<{ [S in K]: UnwrapRef<T[S]> }>
```

This overload will react to changes in the `keys` parameter and modify the returned computed ref accordingly.

### PR DESCRIPTION
**Pull request by TimonLukas**
Closes #460.

This PR adds the ability to pass not only variadic keys, but also an array of keys or a ref array of keys. This is done while (I think) keeping BC. Tests work fine on 3, on 2 Jest completely hangs up got me, even with `--runInBand --detectOpenHandles --forceExit`. I hope these are the usual Jest shenanigans and not a real problem.

### CODE REVIEW

**Comment by TimonLukas** [comment]
It appears the Jest problems are not local to my computer. I'll try to debug them, but help would be greatly appreciated - this seems really weird!

**Comment by antfu** [comment]
Thanks for your contributions, but I am afraid if it's a good idea to introduce such complexity to these simple utils. I saw you found a solution for your problem https://github.com/vueuse/vueuse/issues/460#issuecomment-821888254, do you still feel these changes needed? (since that approach is much cleaner 👍)

Thanks!

**Comment by TimonLukas** [comment]
I think it could still be useful, but you're right that the increased complexity probably isn't worth it :)

**Comment by antfu** [comment]
Maybe we can further break it down into smaller functions to compose it. A good one might be `replaceReactive` there will delete extras keys when the target does not have them. So we can separate the concern and make the codebase more maintainable. WDTY? If you want, feel free to open a new PR. Thanks

**Comment by antfu** [comment]
Thanks for contributions. Close for now.

**Pull request closed without merging**
