### PR TITLE
fix(useDropZone): fix file types filter

### PR DESCRIPTION
**Pull request by getname1997**
fix:修复dragenter阶段event.dataTransfer!.types 类型错误的问题

### CODE REVIEW

**Comment by antfu** [comment]
Can you explain a bit more? Thanks

**Comment by getname1997** [comment]
event.dataTransfer!.types 只能判断出是不是文件，无法精确判断出具体文件类型，具体文件要通过event?.dataTransfer?.items进一步判断，示例是通过useEventListener(pngRef, 'dragstart', (event) => {
  event.dataTransfer?.setData('image/png', '/vue.png')
})强制更改的。

**Comment by getname1997** [comment]
> 你能再解释一下吗？谢谢

fix (useDropZone): The issue of uploading dataTypes attributes directly from a folder without validity

**Comment by AnotiaWang** [comment]
Same issue

**Comment by getname1997** [comment]
> 同样的问题

The actual limitation in his example is the image/png format. You can upload the png format from outside to see

**Pull request merged**
