### PR TITLE
fix(useWebSocket): ssr support

### PR DESCRIPTION
**Pull request by huangyan321**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Additional context

---

### <samp>🤖 Generated by Copilot at a4bc9c6</samp>

Improved `useWebSocket` compatibility and code quality. Added guards for non-browser contexts and simplified event listener logic.

### <samp>🤖 Generated by Copilot at a4bc9c6</samp>

* Import `isClient` utility function to check for browser environment ([link](https://github.com/vueuse/vueuse/pull/3370/files?diff=unified&w=0#diff-9b23df18f0f5236a301bc5926a49b4e0ea571aa84752304cc34a2f44047fa0f1L4-R4))
* Guard `close` and `open` functions with `isClient` to prevent errors with WebSocket API in non-browser contexts ([link](https://github.com/vueuse/vueuse/pull/3370/files?diff=unified&w=0#diff-9b23df18f0f5236a301bc5926a49b4e0ea571aa84752304cc34a2f44047fa0f1L189-R189), [link](https://github.com/vueuse/vueuse/pull/3370/files?diff=unified&w=0#diff-9b23df18f0f5236a301bc5926a49b4e0ea571aa84752304cc34a2f44047fa0f1L291-R297))
* Simplify `useEventListener` call to use default `window` target for `beforeunload` event ([link](https://github.com/vueuse/vueuse/pull/3370/files?diff=unified&w=0#diff-9b23df18f0f5236a301bc5926a49b4e0ea571aa84752304cc34a2f44047fa0f1L291-R297))

### CODE REVIEW

**Review by antfu — APPROVED** [review]

**Comment by hpeevmb** [comment]
Hello, I just experienced problems with those changes. 
I use useWebSocket in a web worker.
When open() is called it does not initiate ws connection, because the worker is not identified as client (isClient is false).

What would be the correct way to use useWebSocket in a web worker?

**Comment by laterdayi** [comment]
This PR causes the webWorker environment to fail to run

**Comment by hpeevmb** [comment]
@laterdayi , PR that addresses the issue is already submitted. Have a look at https://github.com/vueuse/vueuse/pull/3469

**Comment by laterdayi** [comment]
Yes, but the PR didn't merge, so now many projects can only roll back versions

**Pull request merged**
