### PR TITLE
feat(uni-app): new package

### PR DESCRIPTION
**Pull request by okxiaoliang4**
## `packages/core`

<details>
  <summary>Supported</summary>
  <ul>
    <li>asyncComputed - Supported</li>
    <li>autoResetRef - Supported</li>
    <li>computedInject - Supported</li>
    <li>createUnrefFn - Supported</li>
    <li>templateRef - Supported</li>
    <li>useAsyncQueue - Supported</li>
    <li>useAsyncState - Supported</li>
    <li>useClamp - Supported</li>
    <li>useConfirmDialog - Supported</li>
    <li>useCycleList - Supported</li>
    <li>useDebouncedRefHistory - Supported</li>
    <li>useMounted - Supported</li>
    <li>useManualRefHistory - Supported</li>
    <li>useNow - Supported</li>
    <li>useRefHistory - Supported</li>
    <li>useThrottledRefHistory - Supported</li>
    <li>useTimeAgo - Supported</li>
    <li>useTimestamp - Supported</li>
    <li>useVModel - Supported</li>
    <li>useVModels - Supported</li>
  </ul>
</details>

<details>
  <summary>Need Adapter</summary>
  <ul>
    <li>useBase64 - Need Adapter</li>
    <li>useBattery - Need Adapter</li>
    <li>useClipboard - Need Adapter</li>
    <li>useDeviceMotion - Need Adapter</li>
    <li>useDeviceOrientation - Need Adapter</li>
    <li>useDevicePixelRatio - Need Adapter</li>
    <li>useDocumentVisibility - Need Adapter</li>
    <li>useElementBounding - Need Adapter</li>
    <li>useElementHover - Need Adapter</li>
    <li>useElementSize - Need Adapter</li>
    <li>useElementVisibility - Need Adapter</li>
    <li>useFetch - Need Adapter</li>
    <li>useFps - Need Adapter</li>
    <li>useGeolocation - Need Adapter</li>
    <li>useIdle - Need Adapter</li>
    <li>useIntersectionObserver - Need Adapter</li>
    <li>useLocalStorage - Need Adapter</li>
    <li>useMediaControls - Need Adapter</li>
    <li>useMutationObserver - Need Adapter</li>
    <li>useNavigatorLanguage - Need Adapter</li>
    <li>useNetwork - Need Adapter</li>
    <li>useOnline - Need Adapter</li>
    <li>usePreferredColorScheme - Need Adapter</li>
    <li>usePreferredDark - Need Adapter</li>
    <li>usePreferredLanguages - Need Adapter</li>
    <li>useResizeObserver - Need Adapter</li>
    <li>useRafFn - Need Adapter</li>
    <li>useScreenSafeArea - Need Adapter</li>
    <li>useScroll - Need Adapter</li>
    <li>useSessionStorage - Need Adapter</li>
    <li>useShare - Need Adapter</li>
    <li>useStorage - Need Adapter</li>
    <li>useStorageAsync - Need Adapter</li>
    <li>useSwipe - Need Adapter</li>
    <li>useTitle - Need Adapter</li>
    <li>useTransition - Need Adapter</li>
    <li>useUrlSearchParams - Need Adapter</li>
    <li>useWakeLock - Need Adapter [WakeLock](https://developers.weixin.qq.com/miniprogram/dev/api/device/screen/wx.setKeepScreenOn.html)</li>
    <li>useWebSocket - Need Adapter</li>
    <li>useWebWorker - Need Adapter</li>
    <li>useWindowScroll - Need Adapter</li>
    <li>useWindowSize - Need Adapter</li>
  </ul>
</details>

<details>
  <summary>Redo</summary>
  <ul>
    <li>useDark - Redo</li>
    <li>useMemory - Redo</li>
    <li>useFullscreen - Redo</li>
    <li>usePermission - Redo</li>
    <li>useTextSelection - Redo</li>
    <li>useUserMedia - Redo</li>
  </ul>
</details>

<details>
  <summary>Not sure</summary>
  <ul>
    <li>useBreakpoints - Not sure</li>
    <li>useColorMode - Not sure</li>
    <li>useCssVar - Not sure</li>
    <li>useDraggable - Not sure</li>
    <li>useEventBus - Not sure</li>
    <li>useEventListener - Not sure</li>
    <li>useEventSource - Not sure</li>
    <li>useFocus - Not sure</li>
    <li>useFocusWithin - Not sure</li>
    <li>useMediaQuery - Not sure</li>
    <li>useParallax - Not sure</li>
    <li>useScrollLock - Not sure</li>
    <li>useTemplateRefsList - Not sure</li>
    <li>useVirtualList - Not sure</li>
  </ul>
</details>

<details>
  <summary>Not Support</summary>
  <ul>
    <li>onClickOutside - Not Support miniprogram</li>
    <li>onStartTyping - Not Support miniprogram</li>
    <li>unrefElement - Not Support miniprogram</li>
    <li>useActiveElement - Not Support miniprogram</li>
    <li>useBrowserLocation - Not Support miniprogram</li>
    <li>useDevicesList - Not Support miniprogram</li>
    <li>useDisplayMedia - Not Support miniprogram</li>
    <li>useElementByPoint - Not Support miniprogram</li>
    <li>useEyeDropper - Not Support miniprogram</li>
    <li>useFavicon - Not Support miniprogram</li>
    <li>useKeyModifier - Not Support miniprogram</li>
    <li>useMagicKeys - Not Support miniprogram</li>
    <li>useMouse - Not Support miniprogram</li>
    <li>useMouseInElement - Not Support miniprogram</li>
    <li>useMousePressed - Not Support miniprogram</li>
    <li>usePageLeave - Not Support miniprogram</li>
    <li>usePointer - Not Support miniprogram</li>
    <li>usePointerSwipe - Not Support miniprogram</li>
    <li>useScriptTag - Not Support miniprogram</li>
    <li>useSpeechRecognition - Not Support miniprogram</li>
    <li>useSpeechSynthesis - Not Support miniprogram</li>
    <li>useWebWorkerFn - Not Support miniprogram</li>
    <li>useWindowFocus - Not Support miniprogram</li>
  </ul>
</details>

## `packages/shared`

<details>
  <summary>All support🎉.</summary>
  <ul>
    <li>and - Supported</li>
    <li>biSyncRef - Supported</li>
    <li>controlledComputed - Supported</li>
    <li>controlledRef - Supported</li>
    <li>createEventHook - Supported</li>
    <li>createGlobalState - Supported</li>
    <li>createReactiveFn - Supported</li>
    <li>createSharedComposable - Supported</li>
    <li>debouncedRef - Supported</li>
    <li>debouncedWatch - Supported</li>
    <li>eagerComputed - Supported</li>
    <li>extendRef - Supported</li>
    <li>get - Supported</li>
    <li>ignorableWatch - Supported</li>
    <li>isDefined - Supported</li>
    <li>makeDestructurable - Supported</li>
    <li>not - Supported</li>
    <li>or - Supported</li>
    <li>pausableWatch - Supported</li>
    <li>reactify - Supported</li>
    <li>reactifyObject - Supported</li>
    <li>reactivePick - Supported</li>
    <li>refDefault - Supported</li>
    <li>set - Supported</li>
    <li>syncRef - Supported</li>
    <li>throttledRef - Supported</li>
    <li>throttledWatch - Supported</li>
    <li>toReactive - Supported</li>
    <li>toRefs - Supported</li>
    <li>tryOnBeforeUnmount - Supported</li>
    <li>tryOnMounted - Supported</li>
    <li>tryOnScopeDispose - Supported</li>
    <li>tryOnUnmounted - Supported</li>
    <li>until - Supported</li>
    <li>useCounter - Supported</li>
    <li>useDebounce - Supported</li>
    <li>useDebounceFn - Supported</li>
    <li>useInterval - Supported</li>
    <li>useIntervalFn - Supported</li>
    <li>useLastChanged - Supported</li>
    <li>useThrottle - Supported</li>
    <li>useThrottleFn - Supported</li>
    <li>useTimeout - Supported</li>
    <li>useTimeoutFn - Supported</li>
    <li>useToggle - Supported</li>
    <li>watchAtMost - Supported</li>
    <li>watchOnce - Supported</li>
    <li>watchWithFilter - Supported</li>
    <li>whenever - Supported</li>
  </ul>
</details>

## `packages/router`

<details>
  <summary>Need Adapter</summary>
  <ul>
    <li>useRouteQuery - Need Adapter</li>
    <li>useRouteHash - Need Adapter</li>
  </ul>
</details>

## `packages/integrations`

<details>
  <summary>Supported</summary>
  <ul>
    <li>useFuse - Supported</li>
    <li>useJwt - Supported</li>
  </ul>
</details>

<details>
  <summary>Need Adapter</summary>
  <ul>
    <li>useAxios - Need Adapter</li>
    <li>useNProgress - Need Adapter</li>
    <li>useQRCode - Need Adapter</li>
  </ul>
</details>

<details>
  <summary>Not Support</summary>
  <ul>
    <li>useCookies - Not Support miniprogram</li>
    <li>useDrauu - Not Support miniprogram</li>
    <li>useFocusTrap - Not Support miniprogram</li>
  </ul>
</details>

### CODE REVIEW

**Comment by antfu** [comment]
Can you explain a bit about why we need this?

**Comment by okxiaoliang4** [comment]
[uni-app](https://github.com/dcloudio/uni-app)支持vue 3.0语法开发H5和多平台小程序，我想可以搞多个package来在uini-app中兼容各个环境，目前只是尝试性进行探究可行性，开启一个draft pr是为了看看大家对这个package有什么想法，并且也可以看到进行到哪步了~

**Comment by okxiaoliang4** [comment]
@antfu 或许你有什么建议吗？

**Comment by wheatjs** [comment]
Just a heads up, pings aren't necessary. We'll see PRs and comments on them without pings

**Comment by antfu** [comment]
I would think functions in VueUse should work universally in different environments whenever possible. Any special requirement for uni-app?

**Comment by okxiaoliang4** [comment]
I'll try to support it in `package/core` first?

**Comment by okxiaoliang4** [comment]
In the miniprogram environment has to many differences, this is the reason why I want to start a new package.

**Comment by antfu** [comment]
If it's too different from the open Web, maybe it's out-of-scope of VueUse. I'd suggest you creating a new project for it.

**Comment by okxiaoliang4** [comment]
Maybe we can create an adapter like this?

```typescript
// shared/adapter/setTitle.ts
import { defaultDocument } from '@vueuse/core'
import { isClient, isUni } from '../utils/is'

/**
 * set title
 * @param title
 */
export function setTitle(title: string, options: {
  document?: Document
} = {}) {
  if (isClient) {
    const { document = defaultDocument } = options
    if (document) document.title = title
  }
  else if (isUni) { uni.setNavigationBarTitle({ title }) }
}
```
then 
```typescript
// useTitle 
watch(
  title,
  (t, o) => {
    if (isString(t) && t !== o) {
      // before document.title = t
      // after
      setTitle(t, {
        document,
      })
    }
  },
  { immediate: true },
)
```

**Comment by antfu** [comment]
I am sorry, I think VueUse as an open-source project, we want to align with the open standards. While mini apps are proprietary platforms that not everybody as using and are also almost impossible to test. I am gonna reject this package. As mentioned, it could be a good chance for you to create a new personal project for it if you absolutely need it.

**Comment by okxiaoliang4** [comment]
Move to [@uni-helper/uni-use](https://github.com/uni-helper/uni-use)

**Pull request closed without merging**
